"""Module for reading cached League of Legends champion and item data.

Data is generated by the data_updater module (which uses lolstaticdata to
pull from the League Wiki, Data Dragon, and Community Dragon).  This module
only reads from the local cache in the ``data/`` directory.
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from .rune_parser import RESERVED_CACHE_KEYS

DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"


@lru_cache(maxsize=8)
def _read_json_version(data_path: Path, _modified_ns: int) -> dict[str, Any]:
    """Parse one immutable on-disk JSON version.

    ``modified_ns`` exists to make the file version part of the cache key; the
    path alone would keep serving stale data after ``data_updater`` replaces a
    cache file.
    """
    with open(data_path, "r", encoding="utf-8") as data_file:
        return json.load(data_file)


@lru_cache(maxsize=8)
def _resolved(data_directory: Path, filename: str) -> Path:
    """The canonical path of one cache file.

    Canonicalization is what lets two spellings of the same directory share a
    parse, and it is a filesystem call that answers the same for the life of
    the process — the file's *contents* move, its true path does not.  The
    freshness check is the ``stat`` in :func:`_cache_version`, which is not
    memoized.
    """
    return (data_directory / filename).resolve()


def _cache_version(data_directory: Path, filename: str) -> tuple[Path, int]:
    """The ``(canonical path, mtime)`` key every derivation of a cache shares."""
    data_path = _resolved(data_directory, filename)
    return data_path, data_path.stat().st_mtime_ns


def _read_cache(data_directory: Path, filename: str) -> dict[str, Any]:
    """Read cached data, parsing each path-and-mtime version only once."""
    return _read_json_version(*_cache_version(data_directory, filename))


def _validate_champion_data(data: dict[str, Any]) -> None:
    """Validate that champion data has the expected structure.

    Raises:
        ValueError: If the data structure is invalid.
    """
    if not isinstance(data, dict):
        raise ValueError("Champion data must be a dictionary")

    if len(data) == 0:
        raise ValueError("Champion data is empty")

    sample_key = next(iter(data))
    sample_champion = data[sample_key]

    required_fields = ["name", "stats"]
    for field in required_fields:
        if field not in sample_champion:
            raise ValueError(f"Champion data missing required field: '{field}'")


def _validate_item_data(data: dict[str, Any]) -> None:
    """Validate that item data has the expected structure.

    Raises:
        ValueError: If the data structure is invalid.
    """
    if not isinstance(data, dict):
        raise ValueError("Item data must be a dictionary")

    if len(data) == 0:
        raise ValueError("Item data is empty")

    sample_key = next(iter(data))
    sample_item = data[sample_key]

    required_fields = ["name", "stats"]
    for field in required_fields:
        if field not in sample_item:
            raise ValueError(f"Item data missing required field: '{field}'")


def fetch_champion_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read champion data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of champion data keyed by champion identifier.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "champions.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No champion data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    _validate_champion_data(data)
    return data


def fetch_item_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read item data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of item data keyed by item identifier.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "items.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No item data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    _validate_item_data(data)
    return data


def fetch_rune_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read keystone rune data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of rune payloads keyed by rune name, plus the page-level
        blocks named by ``rune_parser.RESERVED_CACHE_KEYS`` (the stat-shard
        table and the adaptive-force conversion), which are not runes.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "runes.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No rune data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    if not isinstance(data, dict) or not data:
        raise ValueError("Rune data must be a non-empty dictionary")
    runes = [entry for name, entry in data.items() if name not in RESERVED_CACHE_KEYS]
    if not runes:
        raise ValueError("Rune data holds no runes")
    if "name" not in runes[0]:
        raise ValueError("Rune data missing required field: 'name'")
    return data


def get_champion(name: str, data_directory: Path = DEFAULT_DATA_DIR) -> dict[str, Any]:
    """Get data for a specific champion by name.

    Args:
        name: Champion name (e.g., "Ahri").
        data_directory: Directory where cached data is stored.

    Returns:
        Champion data dictionary.

    Raises:
        KeyError: If the champion is not found.
    """
    champions = fetch_champion_data(data_directory=data_directory)
    if name in champions:
        return champions[name]
    # Fallback: search by display name (e.g. "Kog'Maw" vs data key "KogMaw")
    for champ_data in champions.values():
        if champ_data.get("name") == name:
            return champ_data
    raise KeyError(f"Champion '{name}' not found in data")


@lru_cache(maxsize=8)
def _item_name_index(data_path: Path, _modified_ns: int) -> dict[str, dict[str, Any]]:
    """``{lowered display name: record}`` for one on-disk items version.

    Earliest spelling wins, which is the answer the linear scan this replaces
    gave: it returned the first record whose name matched.  Keyed on the same
    path-and-mtime version as the parse, so a replaced cache file is a
    different key rather than a stale index.
    """
    index: dict[str, dict[str, Any]] = {}
    for item_data in _read_json_version(data_path, _modified_ns).values():
        index.setdefault(item_data.get("name", "").lower(), item_data)
    return index


def get_item_by_name(
    name: str, data_directory: Path = DEFAULT_DATA_DIR
) -> dict[str, Any]:
    """Get data for a specific item by name.

    Args:
        name: Item name (e.g., "Liandry's Torment").
        data_directory: Directory where cached data is stored.

    Returns:
        Item data dictionary.

    Raises:
        KeyError: If the item is not found.
    """
    fetch_item_data(data_directory=data_directory)
    found = _item_name_index(*_cache_version(data_directory, "items.json")).get(
        name.lower()
    )
    if found is None:
        raise KeyError(f"Item '{name}' not found in data")
    return found
