"""Module for reading cached League of Legends champion and item data.

Data is generated by the data_updater module (which uses lolstaticdata to
pull from the League Wiki, Data Dragon, and Community Dragon).  This module
only reads from the local cache in the ``data/`` directory.
"""

import json
import time
from functools import lru_cache
from pathlib import Path
from typing import Any

DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"

# Cache is considered stale after 24 hours
CACHE_MAX_AGE_SECONDS = 24 * 60 * 60


@lru_cache(maxsize=8)
def _read_json_version(data_path: Path, _modified_ns: int) -> dict[str, Any]:
    """Parse one immutable on-disk JSON version.

    ``modified_ns`` exists to make the file version part of the cache key; the
    path alone would keep serving stale data after ``data_updater`` replaces a
    cache file.
    """
    with open(data_path, "r", encoding="utf-8") as data_file:
        return json.load(data_file)


def _get_cache_metadata_path(data_directory: Path, filename: str) -> Path:
    """Return the path to the cache metadata file for a given data file."""
    return data_directory / f".{filename}.meta"


def _is_cache_valid(
    data_directory: Path,
    filename: str,
    max_age_seconds: int = CACHE_MAX_AGE_SECONDS,
) -> bool:
    """Check whether the cached file exists and is not stale."""
    data_path = data_directory / filename
    meta_path = _get_cache_metadata_path(data_directory, filename)

    if not data_path.exists() or not meta_path.exists():
        return False

    try:
        with open(meta_path, "r", encoding="utf-8") as meta_file:
            metadata = json.load(meta_file)
        fetched_at = metadata.get("fetched_at", 0)
        return (time.time() - fetched_at) < max_age_seconds
    except (json.JSONDecodeError, OSError):
        return False


def _write_cache(data_directory: Path, filename: str, data: dict[str, Any]) -> None:
    """Write data and metadata to the cache directory."""
    data_directory.mkdir(parents=True, exist_ok=True)

    data_path = data_directory / filename
    meta_path = _get_cache_metadata_path(data_directory, filename)

    with open(data_path, "w", encoding="utf-8") as data_file:
        json.dump(data, data_file, indent=2)
    _read_json_version.cache_clear()

    metadata = {"fetched_at": time.time(), "filename": filename}
    with open(meta_path, "w", encoding="utf-8") as meta_file:
        json.dump(metadata, meta_file, indent=2)


def _read_cache(data_directory: Path, filename: str) -> dict[str, Any]:
    """Read cached data, parsing each path-and-mtime version only once."""
    data_path = (data_directory / filename).resolve()
    return _read_json_version(data_path, data_path.stat().st_mtime_ns)


def _validate_champion_data(data: dict[str, Any]) -> None:
    """Validate that champion data has the expected structure.

    Raises:
        ValueError: If the data structure is invalid.
    """
    if not isinstance(data, dict):
        raise ValueError("Champion data must be a dictionary")

    if len(data) == 0:
        raise ValueError("Champion data is empty")

    sample_key = next(iter(data))
    sample_champion = data[sample_key]

    required_fields = ["name", "stats"]
    for field in required_fields:
        if field not in sample_champion:
            raise ValueError(f"Champion data missing required field: '{field}'")


def _validate_item_data(data: dict[str, Any]) -> None:
    """Validate that item data has the expected structure.

    Raises:
        ValueError: If the data structure is invalid.
    """
    if not isinstance(data, dict):
        raise ValueError("Item data must be a dictionary")

    if len(data) == 0:
        raise ValueError("Item data is empty")

    sample_key = next(iter(data))
    sample_item = data[sample_key]

    required_fields = ["name", "stats"]
    for field in required_fields:
        if field not in sample_item:
            raise ValueError(f"Item data missing required field: '{field}'")


def fetch_champion_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read champion data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of champion data keyed by champion identifier.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "champions.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No champion data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    _validate_champion_data(data)
    return data


def fetch_item_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read item data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of item data keyed by item identifier.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "items.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No item data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    _validate_item_data(data)
    return data


def fetch_rune_data(
    data_directory: Path = DEFAULT_DATA_DIR,
) -> dict[str, Any]:
    """Read keystone rune data from the local cache.

    Args:
        data_directory: Directory where cached data is stored.

    Returns:
        Dictionary of rune payloads keyed by rune name.

    Raises:
        FileNotFoundError: If no cached data exists.  Run the updater first.
    """
    filename = "runes.json"
    cache_path = data_directory / filename

    if not cache_path.exists():
        raise FileNotFoundError(
            "No rune data found. Click 'Update to latest patch' to fetch data."
        )

    data = _read_cache(data_directory, filename)
    if not isinstance(data, dict) or not data:
        raise ValueError("Rune data must be a non-empty dictionary")
    sample = next(iter(data.values()))
    if "name" not in sample:
        raise ValueError("Rune data missing required field: 'name'")
    return data


def get_champion(name: str, data_directory: Path = DEFAULT_DATA_DIR) -> dict[str, Any]:
    """Get data for a specific champion by name.

    Args:
        name: Champion name (e.g., "Ahri").
        data_directory: Directory where cached data is stored.

    Returns:
        Champion data dictionary.

    Raises:
        KeyError: If the champion is not found.
    """
    champions = fetch_champion_data(data_directory=data_directory)
    if name in champions:
        return champions[name]
    # Fallback: search by display name (e.g. "Kog'Maw" vs data key "KogMaw")
    for champ_data in champions.values():
        if champ_data.get("name") == name:
            return champ_data
    raise KeyError(f"Champion '{name}' not found in data")


def get_item_by_name(
    name: str, data_directory: Path = DEFAULT_DATA_DIR
) -> dict[str, Any]:
    """Get data for a specific item by name.

    Args:
        name: Item name (e.g., "Liandry's Torment").
        data_directory: Directory where cached data is stored.

    Returns:
        Item data dictionary.

    Raises:
        KeyError: If the item is not found.
    """
    items = fetch_item_data(data_directory=data_directory)
    for _, item_data in items.items():
        if item_data.get("name", "").lower() == name.lower():
            return item_data
    raise KeyError(f"Item '{name}' not found in data")
