"""Aurelion Sol's Stardust count."""

from typing import Any

from ..config import _seeded_option_stacks
from ..results import RotationResult
from ..state import FightState
from .account import StackEvent, _resource_ledger, _StackAccount


def _add_aurelion_sol_stardust(state: FightState, rotation: RotationResult) -> None:
    """Add Aurelion Sol's Cosmic Creator Stardust counter ledger (P3 3X).

    Stardust is a PERMANENT counter generated by damaging abilities; the
    only ACCEPTED live gain the engine certifies is the Q burst against
    the champion target (+2 per burst — game QMassStolen 2.0, wiki "the
    beam will deal a burst ... and additionally generates 2 Stardust if
    they are a champion").  Champion takedowns grant NO Stardust (they
    only refund W's cooldown), so the Senna takedown synthesis is NOT
    reused — a takedown event is a named denial.  The walk is
    documentary: it receipts the gains, the per-100 display milestones,
    and the fail-closed denials into an additive
    ``resource_ledger["stardust"]`` (kind "stardust") sub-section — the
    mana account is never replaced — and never re-prices any damage.
    """
    if "stardust_stacks" not in (state.champion_options):
        return
    from ...champions.aurelion_sol_stardust import (
        _Q_BURSTS_PER_CHANNEL,
        _STARDUST_PER_Q_BURST,
        AURELION_SOL_STARDUST_RULE,
    )

    option = state.champion_options
    seeded = _seeded_option_stacks(
        option, "champion", "Aurelion Sol", "stardust_stacks"
    )
    account = _StackAccount("stardust", seeded, 999)
    milestones: list[dict[str, Any]] = []
    # The accepted stream: one Q burst vs the champion target per full
    # second of channel (timed) or 3 per Q cast (one-rotation/auto-only),
    # mirroring the module's _channel_window semantics from state fields.
    q_casts = [
        event for event in rotation.cast_events if str(event.get("slot", "")) == "Q"
    ]
    timed = not (state.one_rotation or state.auto_attacks_only)
    bursts_per_cast = (
        int(state.fight_duration_seconds) if timed else _Q_BURSTS_PER_CHANNEL
    )
    if q_casts and bursts_per_cast > 0:
        for cast in q_casts:
            cast_time = float(cast.get("time", 0.0))
            ordinal = int(cast.get("ordinal", 0) or 0)
            for burst_index in range(bursts_per_cast):
                account.add(
                    StackEvent(
                        "gain",
                        _STARDUST_PER_Q_BURST,
                        cast_time,
                        "q_burst_champion",
                        accepted=True,
                        reason="",
                        fields={
                            "event": "q_burst",
                            "source_key": "Q",
                            "cast_ordinal": ordinal,
                            "burst_index": burst_index + 1,
                            "event_time": round(cast_time, 3),
                        },
                    )
                )
    else:
        account.add(
            StackEvent(
                "gain",
                0.0,
                0.0,
                "q_burst_champion",
                accepted=False,
                reason="no_q_burst_event",
            )
        )

    # Named fail-closed denials for the unsupported Stardust sources.
    for source in (
        "champion_takedown",
        "e_champion_seconds",
        "e_kill_bounty",
        "r_multihit",
        "minion_farm",
    ):
        account.add(
            StackEvent(
                "gain",
                0.0,
                0.0,
                f"unsupported_stardust_source:{source}",
                accepted=False,
                reason=f"unsupported_stardust_source:{source}",
                fields={"event": source, "event_time": 0.0},
            )
        )
    account.add(
        StackEvent(
            "gain",
            0.0,
            0.0,
            "stardust_event_without_identity",
            accepted=False,
            reason="missing_identity",
        )
    )

    # Per-100 display milestones: both priced terms are LINEAR — the rows
    # document the display values and never re-price (mechanical False).
    step = AURELION_SOL_STARDUST_RULE.execute_breakpoint_stacks
    milestone = seeded // step * step + step
    while milestone <= account.current:
        k = milestone // step
        milestones.append(
            {
                "threshold": milestone,
                "threshold_count": milestone,
                "q_burst_maxhp_pct": (
                    AURELION_SOL_STARDUST_RULE.q_burst_maxhp_pct_per_100 * k
                ),
                "e_execute_threshold_pct": (
                    AURELION_SOL_STARDUST_RULE.e_execute_base_pct
                    + AURELION_SOL_STARDUST_RULE.e_execute_pct_per_100 * k
                ),
                "execute_pct_delta": AURELION_SOL_STARDUST_RULE.e_execute_pct_per_100,
                "mechanical": False,
                "stacks_before": milestone - step,
                "stacks_after": milestone,
                "stat_application": "parse_time_seeded",
            }
        )
        milestone += step

    _resource_ledger(rotation)["stardust"] = account.ledger_section(
        seeded, milestones, AURELION_SOL_STARDUST_RULE.public_receipt()
    )
    state.breakdown["stardust"] = {
        "name": AURELION_SOL_STARDUST_RULE.public_receipt()["name"],
        "owner": "champion",
        "informational": True,
        "event_phase": "effect",
        "count": account.gains,
        "starting_stacks": seeded,
        "state": f"{seeded} seeded Stardust; {account.current} at fight end",
        "max_stacks": 999,
        "gain_events": [
            receipt for receipt in account.receipts if receipt["operation"] == "gain"
        ],
        "threshold_transitions": milestones,
    }
    if account.gains:
        state.notes.append(
            f"Aurelion Sol Stardust: {account.current} stacks at fight end "
            f"({account.gains} Q-burst champion hit(s) gained over the seeded "
            f"{seeded})."
        )
    else:
        state.notes.append(
            f"Aurelion Sol Stardust: {account.current} stacks (no Q burst — the "
            "seeded counter is the whole admission; E champion-seconds, E "
            "kill bounties, R multihits, and minion farming are named "
            "unsupported sources)."
        )
