"""Rule-5 lint: the scanned files read no cached data behind a literal default.

`scripts/literal_defaults.py` flags `.get("key", <literal>)`, `<get> or
<literal>` and `getattr(o, "attr", <literal>)`, exempting an index into a
local accumulator and a None-coalesce by shape.  What survives is frozen here
by module path, enclosing function, key and how many times that key occurs
there — never by line number, so an edit above a site does not turn this red
while a second site under an already-frozen key still does.

`ROOTS` is the covered set: every `.py` under it is scanned, including the
ones that currently survive nothing, so a new literal default in a clean
champion module is caught the day it is written.  A file joins `ROOTS` only
once every site in it is either converted or sorted into a bucket below.
"""

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

import literal_defaults

CALCULATOR = Path(__file__).resolve().parent.parent / "src" / "calculator"

#: Reads off an internal breakdown or damage-event row.  These rows have no
#: schema home the way `_damage_event_row`'s mandatory five do; one row
#: dataclass retires the whole list at once (campaign decision D3, bucket D1).
ROW_READS = frozenset(
    {
        ("damage.py", "_ability_dot_tick_events", "dict.get", '"casts"', 1),
        ("damage.py", "_ability_dot_tick_events", "dict.get", '"total_damage"', 1),
        ("damage.py", "_add_ashe_focus", "dict.get", '"slot"', 1),
        ("damage.py", "_add_ashe_focus", "or-default", '"auto_attacks"', 1),
        ("damage.py", "_add_ashe_focus", "or-default", '"damage_events"', 1),
        ("damage.py", "_add_aurelion_sol_stardust", "dict.get", '"ordinal"', 1),
        ("damage.py", "_add_aurelion_sol_stardust", "dict.get", '"slot"', 1),
        ("damage.py", "_add_aurelion_sol_stardust", "dict.get", '"time"', 1),
        ("damage.py", "_add_aurelion_sol_stardust", "or-default", '"ordinal"', 1),
        (
            "damage.py",
            "_add_copied_stacking_on_hit_packets",
            "dict.get",
            '"packets"',
            1,
        ),
        ("damage.py", "_add_copied_stacking_on_hit_packets", "dict.get", '"time"', 1),
        ("damage.py", "_add_heimerdinger_w_e", "dict.get", '"raw_damage"', 1),
        ("damage.py", "_add_keystone_conqueror", "dict.get", '"reason"', 1),
        ("damage.py", "_add_keystone_conqueror", "dict.get", '"sequence"', 1),
        ("damage.py", "_add_keystone_dark_harvest", "dict.get", '"time"', 1),
        ("damage.py", "_add_keystone_deathfire", "dict.get", '"event_precision"', 1),
        ("damage.py", "_add_rengar_ferocity", "dict.get", '"detail"', 1),
        ("damage.py", "_add_rengar_ferocity", "dict.get", '"ordinal"', 1),
        ("damage.py", "_add_rengar_ferocity", "dict.get", '"reason"', 1),
        ("damage.py", "_add_rengar_ferocity", "dict.get", '"slot"', 2),
        ("damage.py", "_add_rengar_ferocity", "or-default", '"ordinal"', 1),
        ("damage.py", "_add_senna_souls", "dict.get", '"target"', 1),
        ("damage.py", "_add_single_proc_on_hits", "dict.get", '"event_precision"', 1),
        ("damage.py", "_add_spellblade_damage", "dict.get", '"casts"', 1),
        ("damage.py", "_add_stored_damage", "dict.get", '"casts"', 1),
        ("damage.py", "_add_stored_damage", "dict.get", '"slot"', 1),
        ("damage.py", "_add_stored_damage", "dict.get", '"time"', 1),
        ("damage.py", "_apply_command_amp", "or-default", '"damage_events"', 1),
        ("damage.py", "_apply_damage_amplifiers", "dict.get", '"total_damage"', 1),
        ("damage.py", "_apply_mana_resource_limits", "dict.get", '"burst_seconds"', 1),
        ("damage.py", "_apply_mana_resource_limits", "dict.get", '"window_seconds"', 1),
        (
            "damage.py",
            "_apply_temporary_lethality_windows",
            "dict.get",
            '"event_phase"',
            2,
        ),
        (
            "damage.py",
            "_apply_temporary_lethality_windows",
            "dict.get",
            '"total_damage"',
            1,
        ),
        ("damage.py", "_author_ability_dot_events", "dict.get", '"slot"', 1),
        ("damage.py", "_author_empowered_swing_events", "dict.get", '"damage"', 1),
        ("damage.py", "_author_empowered_swing_events", "dict.get", '"damage_type"', 1),
        (
            "damage.py",
            "_author_empowered_swing_events",
            "dict.get",
            '"total_damage"',
            1,
        ),
        ("damage.py", "_conqueror_trigger_events", "dict.get", '"phase"', 1),
        ("damage.py", "_conqueror_trigger_events", "dict.get", '"slot"', 1),
        ("damage.py", "_conqueror_trigger_events", "dict.get", '"time"', 1),
        ("damage.py", "_damaging_cast_times", "dict.get", '"total_raw"', 1),
        ("damage.py", "_dark_harvest_trigger_event", "dict.get", '"phase"', 1),
        ("damage.py", "_deathfire_trigger_events", "dict.get", '"event_precision"', 2),
        ("damage.py", "_deathfire_trigger_events", "dict.get", '"slot"', 1),
        ("damage.py", "_deathfire_trigger_events", "dict.get", '"time"', 1),
        ("damage.py", "_empowered_swing_consumers", "dict.get", '"casts"', 1),
        ("damage.py", "_empowered_swing_consumers", "dict.get", '"slot"', 1),
        ("damage.py", "_event_timeline_coverage", "dict.get", '"casts"', 2),
        ("damage.py", "_event_timeline_coverage", "dict.get", '"event_precision"', 1),
        ("damage.py", "_event_timeline_coverage", "dict.get", '"total_damage"', 1),
        ("damage.py", "_feed_ashe_focus_stack", "dict.get", '"time"', 2),
        ("damage.py", "_feed_ashe_focus_stack", "or-default", '"time"', 1),
        (
            "damage.py",
            "_first_damaging_ability_event",
            "dict.get",
            '"event_precision"',
            1,
        ),
        ("damage.py", "_first_damaging_ability_event", "dict.get", '"total_damage"', 1),
        (
            "damage.py",
            "_first_damaging_ability_event",
            "or-default",
            '"total_damage"',
            1,
        ),
        ("damage.py", "_hypershot_delta_events", "dict.get", '"damage_type"', 1),
        ("damage.py", "_hypershot_delta_events", "dict.get", '"total_damage"', 1),
        ("damage.py", "_impaired_instance_times", "dict.get", '"total_raw"', 1),
        ("damage.py", "_item_proc_precision", "dict.get", '"casts"', 1),
        ("damage.py", "_item_proc_precision", "or-default", '"casts"', 1),
        ("damage.py", "_layer_on_hit_effects", "dict.get", '"casts"', 1),
        ("damage.py", "_muramana_cast_receipt", "dict.get", '"total_damage"', 1),
        ("damage.py", "_muramana_cast_receipt", "or-default", '"total_damage"', 1),
        ("damage.py", "_next_authored_event", "dict.get", '"event_precision"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"casts"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"count"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"slot"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"time"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"total_damage"', 1),
        ("damage.py", "_ordered_damage_events", "dict.get", '"total_raw"', 1),
        ("damage.py", "_ordered_damage_events", "or-default", '"total_raw"', 1),
        ("damage.py", "_reattribute_empowered_swings", "dict.get", '"casts"', 1),
        ("damage.py", "_reattribute_empowered_swings", "dict.get", '"count"', 1),
        (
            "damage.py",
            "_reattribute_empowered_swings",
            "dict.get",
            '"damage_per_hit"',
            1,
        ),
        (
            "damage.py",
            "_resolve_starting_shield_outcome",
            "dict.get",
            '"execute_threshold_ratio"',
            1,
        ),
        (
            "damage.py",
            "_resolve_starting_shield_outcome",
            "dict.get",
            '"raw_damage"',
            1,
        ),
        (
            "damage.py",
            "_resolve_starting_shield_outcome",
            "dict.get",
            '"total_damage"',
            1,
        ),
        (
            "damage.py",
            "_resolve_starting_shield_outcome",
            "or-default",
            '"execute_threshold_ratio"',
            1,
        ),
        (
            "damage.py",
            "_resolve_starting_shield_outcome",
            "or-default",
            '"raw_damage"',
            1,
        ),
        ("damage.py", "_resource_ledger_public", "dict.get", '"bonus_delta"', 1),
        ("damage.py", "_resource_ledger_public", "or-default", '"bonus_delta"', 1),
        ("damage.py", "_return_denied_burst_budget", "dict.get", '"burst_seconds"', 1),
        ("damage.py", "_row_damage_parts", "dict.get", '"total_damage"', 1),
        ("damage.py", "_schedule_enlighten", "dict.get", '"tick"', 1),
        ("damage.py", "_self_shield_times", "dict.get", '"time"', 1),
        ("damage.py", "_slot_ordinals", "dict.get", '"ordinal"', 1),
        ("damage.py", "_slot_ordinals", "dict.get", '"slot"', 1),
        ("damage.py", "_slot_ordinals", "or-default", '"ordinal"', 1),
        (
            "damage.py",
            "_stacked_champion_proc_times",
            "dict.get",
            '"event_precision"',
            1,
        ),
        ("damage.py", "_stacked_champion_proc_times", "dict.get", '"total_damage"', 3),
        ("damage.py", "add", "dict.get", '"cc_duration"', 1),
        ("damage.py", "add", "or-default", '"cc_duration"', 1),
        ("damage.py", "emit_until", "dict.get", '"category"', 1),
        ("damage.py", "emit_until", "dict.get", '"source"', 1),
        ("damage.py", "split_auto_vs_ability", "dict.get", '"total_damage"', 1),
        ("damage.py", "split_by_damage_type", "dict.get", '"total_damage"', 2),
    }
)

#: Request-supplied per-item state, not cached data: an absent key is the
#: item's declared off state, and `ITEM_INPUT_OPTIONS` owns what that is.
REQUEST_ITEM_STATE = frozenset(
    {
        (
            "item_effects.py",
            "actualizer_active_seconds",
            "dict.get",
            '"mana_made_real_active"',
            1,
        ),
        (
            "item_effects.py",
            "actualizer_active_seconds",
            "dict.get",
            '"mana_made_real_active_seconds"',
            1,
        ),
        (
            "item_effects.py",
            "actualizer_active_seconds",
            "or-default",
            '"mana_made_real_active"',
            1,
        ),
        ("item_effects.py", "input_option_crit_chance", "dict.get", '"crit_stacks"', 1),
        (
            "item_effects.py",
            "input_option_retribution_bonus_ad",
            "dict.get",
            '"missing_health_percent"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "dict.get", '"Endless Hunger"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"Heartsteel"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"Hubris"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"Knight\'s Vow"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"Rod of Ages"', 1),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"Tear of the Goddess"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"Yun Tal Wildarrows"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "dict.get", '"bonus_health"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"crit_stacks"', 1),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"eminence_active_seconds"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "dict.get", '"eminence_stacks"', 1),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"feast_active_seconds"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"holder_above_30_percent"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"manaflow_bonus_mana"',
            2,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"missing_health_percent"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"shared_riches_gold"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "dict.get", '"timeless_stacks"', 1),
        ("item_effects.py", "item_state_receipts", "dict.get", '"ward_uses"', 1),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"worthy_target_index"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "dict.get",
            '"worthy_within_range"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "or-default",
            '"Overlord\'s Bloodmail"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "or-default", '"crit_stacks"', 1),
        (
            "item_effects.py",
            "item_state_receipts",
            "or-default",
            '"eminence_active_seconds"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "or-default",
            '"eminence_stacks"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "or-default",
            '"feast_active_seconds"',
            1,
        ),
        (
            "item_effects.py",
            "item_state_receipts",
            "or-default",
            '"shared_riches_gold"',
            1,
        ),
        ("item_effects.py", "item_state_receipts", "or-default", '"ward_uses"', 1),
    }
)

#: Reads on the in-module `ITEM_INPUT_OPTIONS` declaration itself.  An absent
#: facet means this option declares none, which is a source fact, not a
#: cached-data miss.
OPTION_SCHEMA = frozenset(
    {
        (
            "item_effects.py",
            "_input_option_stat_bonuses",
            "dict.get",
            '"bonus_ap_per_unit"',
            1,
        ),
        (
            "item_effects.py",
            "_input_option_stat_bonuses",
            "dict.get",
            '"bonus_health_per_unit"',
            1,
        ),
        (
            "item_effects.py",
            "_input_option_stat_bonuses",
            "dict.get",
            '"bonus_mana_per_unit"',
            1,
        ),
        ("item_effects.py", "_item_option_schemas", "dict.get", '"options"', 1),
        ("item_effects.py", "input_option_float_value", "dict.get", '"step"', 1),
        ("item_effects.py", "input_option_float_value", "or-default", '"step"', 1),
        ("item_effects.py", "validate_item_input_options", "dict.get", '"step"', 1),
        ("item_effects.py", "validate_item_input_options", "or-default", '"step"', 1),
    }
)

#: A loadout row's own name.  The empty string is a sentinel the next
#: statement rejects or skips past; no number rides on it.
LOADOUT_NAMES = frozenset(
    {
        ("item_effects.py", "_cached_sustain_stat", "or-default", '"name"', 1),
        (
            "item_effects.py",
            "_resolve_damage_effects_uncached",
            "dict.get",
            '"name"',
            1,
        ),
        ("item_effects.py", "active_secondary_ad_item_name", "dict.get", '"name"', 1),
        ("item_effects.py", "cleave_on_hit_item_name", "dict.get", '"name"', 1),
        ("item_effects.py", "grouped_sustain_stat_percent", "or-default", '"name"', 1),
        ("item_effects.py", "hydra_secondary_item_name", "dict.get", '"name"', 1),
        ("item_effects.py", "resolve_damage_effects", "dict.get", '"name"', 1),
        ("item_effects.py", "target_class_denials", "dict.get", '"name"', 1),
        ("item_effects.py", "target_class_denials", "or-default", '"name"', 1),
    }
)

#: Atom rows compared against the registry.  The empty tuple is the failure
#: branch: each of these raises on the next line rather than using it.
ATOM_ROWS = frozenset(
    {
        ("item_effects.py", "counter_trigger", "dict.get", '"counter_trigger"', 1),
        ("item_effects.py", "_atom_pinned_value", "dict.get", '"values"', 1),
        (
            "item_effects.py",
            "guardian_angel_rebirth_declaration",
            "dict.get",
            '"values"',
            1,
        ),
        ("item_effects.py", "spell_shield_cooldown_seconds", "dict.get", '"values"', 1),
    }
)

#: Strict traversals of a raw cached ability row.  Every one of these feeds a
#: shape check whose failure branch raises, naming champion, slot and source —
#: the empty default is the path *to* that raise, never a served value.
WIKI_TRAVERSALS = frozenset(
    {
        ("ability_atoms.py", "_valid_atom_hash", "dict.get", '"hash"', 1),
        ("ability_atoms.py", "ranked_ability_atom_value", "dict.get", '"values"', 1),
        ("ability_atoms.py", "required_ability_atom", "dict.get", '"evidence"', 1),
        (
            "ability_atoms.py",
            "required_ranked_attribute_atom",
            "dict.get",
            '"abilities"',
            1,
        ),
        (
            "ability_atoms.py",
            "required_ranked_attribute_atom",
            "dict.get",
            '"attribute"',
            1,
        ),
        (
            "ability_atoms.py",
            "required_ranked_attribute_atom",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "ability_atoms.py",
            "required_ranked_attribute_atom",
            "dict.get",
            '"leveling"',
            1,
        ),
        (
            "ability_atoms.py",
            "required_ranked_attribute_atom",
            "dict.get",
            '"modifiers"',
            1,
        ),
    }
)

#: The same traversal shape as `WIKI_TRAVERSALS`, over the whole covered set:
#: one step of a walk down a raw cached row (champion, item or rune JSON)
#: whose empty default is the path to the branch that refuses — a `return
#: None` that prices the slot at nothing, or a raise naming the source.  No
#: number is ever served from one of these defaults; the walk that would have
#: produced it does not run.  A site that *serves* a cached value belongs in
#: no bucket: it gets a fail-loud accessor instead (`slotlib.ability_name`,
#: `ability_atoms.required_ability_atom`, `item_effects`' typed readers).
CACHED_SOURCE_ROW = frozenset(
    {
        ("champions/aatrox.py", "derive_self_healing", "dict.get", '"description"', 1),
        ("champions/aatrox.py", "derive_self_healing", "dict.get", '"effects"', 1),
        (
            "champions/akshan.py",
            "_extract_double_shot_ratio",
            "dict.get",
            '"description"',
            1,
        ),
        (
            "champions/akshan.py",
            "_extract_double_shot_ratio",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/akshan.py",
            "_parse_passive_proc_damage",
            "dict.get",
            '"description"',
            1,
        ),
        (
            "champions/akshan.py",
            "_parse_passive_proc_damage",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/alistar.py",
            "_extract_e_on_hit_damage",
            "dict.get",
            '"attribute"',
            1,
        ),
        (
            "champions/alistar.py",
            "_extract_e_on_hit_damage",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/alistar.py",
            "_extract_e_on_hit_damage",
            "dict.get",
            '"leveling"',
            1,
        ),
        (
            "champions/alistar.py",
            "_extract_e_on_hit_damage",
            "dict.get",
            '"modifiers"',
            1,
        ),
        ("champions/alistar.py", "_extract_e_on_hit_damage", "dict.get", '"values"', 1),
        ("champions/alistar.py", "derive_self_healing", "dict.get", '"description"', 1),
        ("champions/alistar.py", "derive_self_healing", "dict.get", '"effects"', 1),
        ("champions/ambessa.py", "_drakehounds_step", "dict.get", '"description"', 1),
        ("champions/ambessa.py", "_drakehounds_step", "dict.get", '"effects"', 1),
        (
            "champions/ambessa.py",
            "_parse_passive_damage",
            "dict.get",
            '"description"',
            1,
        ),
        ("champions/ambessa.py", "_parse_passive_damage", "dict.get", '"effects"', 1),
        ("champions/ambessa.py", "_parse_passive_damage", "dict.get", '"modifiers"', 1),
        (
            "champions/ambessa.py",
            "_repudiation_shield_amount",
            "dict.get",
            '"modifiers"',
            1,
        ),
        (
            "champions/ambessa.py",
            "_repudiation_shield_amount",
            "dict.get",
            '"units"',
            1,
        ),
        (
            "champions/ambessa.py",
            "_repudiation_shield_amount",
            "dict.get",
            '"values"',
            1,
        ),
        ("champions/aphelios.py", "derive_self_healing", "dict.get", '"P"', 1),
        ("champions/aphelios.py", "derive_self_healing", "dict.get", '"abilities"', 1),
        ("champions/ashe.py", "_require_q_rows", "dict.get", '"effects"', 1),
        ("champions/ashe.py", "_require_q_rows", "dict.get", '"leveling"', 1),
        (
            "champions/attribute_classifier.py",
            "classify_damage_type",
            "dict.get",
            '"damageType"',
            1,
        ),
        (
            "champions/attribute_classifier.py",
            "classify_damage_type",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/attribute_classifier.py",
            "classify_damage_type",
            "dict.get",
            '"leveling"',
            1,
        ),
        ("champions/azir.py", "_arise", "or-default", '"rechargeRate"', 1),
        ("champions/belveth.py", "_per_level_scaling", "dict.get", '"attribute"', 1),
        ("champions/belveth.py", "_per_level_scaling", "dict.get", '"effects"', 1),
        ("champions/belveth.py", "_per_level_scaling", "dict.get", '"leveling"', 1),
        ("champions/blitzcrank.py", "_static_field", "dict.get", '"attribute"', 1),
        ("champions/blitzcrank.py", "_static_field", "dict.get", '"effects"', 1),
        ("champions/blitzcrank.py", "_static_field", "dict.get", '"leveling"', 1),
        ("champions/blitzcrank.py", "_static_field", "dict.get", '"modifiers"', 1),
        ("champions/blitzcrank.py", "_static_field", "dict.get", '"units"', 1),
        (
            "champions/cassiopeia.py",
            "_bonus_magic_damage_levelings",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/cassiopeia.py",
            "_bonus_magic_damage_levelings",
            "dict.get",
            '"leveling"',
            1,
        ),
        ("champions/darius.py", "_per_level", "dict.get", '"effects"', 1),
        ("champions/darius.py", "_per_level", "dict.get", '"leveling"', 1),
        ("champions/engine.py", "_stamp_slot_facts", "dict.get", '"spellEffects"', 1),
        ("champions/engine.py", "parse_abilities", "dict.get", '"abilities"', 1),
        ("champions/engine.py", "parse_abilities", "dict.get", '"resource"', 1),
        ("champions/gangplank.py", "_require_w_rows", "dict.get", '"effects"', 1),
        ("champions/gangplank.py", "_require_w_rows", "dict.get", '"leveling"', 1),
        ("champions/gangplank.py", "_require_w_rows", "dict.get", '"modifiers"', 1),
        ("champions/garen.py", "derive_self_healing", "dict.get", '"effects"', 1),
        ("champions/garen.py", "derive_self_healing", "dict.get", '"leveling"', 1),
        ("champions/garen.py", "derive_self_healing", "dict.get", '"modifiers"', 1),
        ("champions/garen.py", "derive_self_healing", "dict.get", '"values"', 1),
        ("champions/gragas.py", "derive_self_healing", "dict.get", '"description"', 1),
        ("champions/gragas.py", "derive_self_healing", "dict.get", '"effects"', 1),
        ("champions/gwen.py", "_snip_times", "dict.get", '"castTime"', 1),
        ("champions/heimerdinger.py", "_require_row", "dict.get", '"effects"', 1),
        ("champions/heimerdinger.py", "_require_row", "dict.get", '"leveling"', 1),
        ("champions/jayce.py", "_transform_ability", "dict.get", '"R"', 1),
        (
            "champions/karthus.py",
            "_defile_mana_per_second",
            "dict.get",
            '"modifiers"',
            1,
        ),
        ("champions/karthus.py", "_defile_mana_per_second", "dict.get", '"values"', 1),
        ("champions/karthus.py", "_defile_mana_per_second", "or-default", '"cost"', 1),
        ("champions/ksante.py", "_require_row", "dict.get", '"effects"', 1),
        ("champions/ksante.py", "_require_row", "dict.get", '"leveling"', 1),
        ("champions/maokai.py", "derive_self_healing", "dict.get", '"modifiers"', 1),
        ("champions/maokai.py", "derive_self_healing", "dict.get", '"values"', 1),
        ("champions/maokai.py", "derive_self_healing", "or-default", '"cooldown"', 1),
        (
            "champions/mel.py",
            "_searing_brilliance_per_missile",
            "or-default",
            '"modifiers"',
            2,
        ),
        (
            "champions/mel.py",
            "_searing_brilliance_per_missile",
            "or-default",
            '"values"',
            2,
        ),
        (
            "champions/miss_fortune.py",
            "_love_tap_ad_ratio",
            "or-default",
            '"modifiers"',
            1,
        ),
        (
            "champions/miss_fortune.py",
            "_love_tap_ad_ratio",
            "or-default",
            '"values"',
            1,
        ),
        ("champions/mordekaiser.py", "parse", "dict.get", '"description"', 1),
        ("champions/mordekaiser.py", "parse", "dict.get", '"effects"', 1),
        (
            "champions/ornn.py",
            "_temper_consume_percent",
            "or-default",
            '"description"',
            1,
        ),
        ("champions/ornn.py", "_temper_consume_percent", "or-default", '"effects"', 1),
        ("champions/rengar.py", "_ferocity_bonus", "dict.get", '"description"', 1),
        ("champions/rengar.py", "_ferocity_bonus", "dict.get", '"effects"', 1),
        ("champions/sett.py", "_haymaker", "dict.get", '"modifiers"', 1),
        ("champions/sett.py", "_haymaker", "dict.get", '"units"', 1),
        ("champions/sett.py", "_haymaker", "dict.get", '"values"', 1),
        ("champions/sett.py", "_knuckle_down", "dict.get", '"modifiers"', 1),
        ("champions/sett.py", "_knuckle_down", "dict.get", '"units"', 1),
        ("champions/sett.py", "_knuckle_down", "dict.get", '"values"', 1),
        ("champions/sett.py", "derive_self_healing", "dict.get", '"description"', 1),
        ("champions/sett.py", "derive_self_healing", "dict.get", '"effects"', 1),
        (
            "champions/shen.py",
            "_ki_barrier_shield_amount",
            "dict.get",
            '"modifiers"',
            1,
        ),
        ("champions/shen.py", "_ki_barrier_shield_amount", "dict.get", '"units"', 1),
        ("champions/shen.py", "_ki_barrier_shield_amount", "dict.get", '"values"', 1),
        ("champions/shen.py", "_named_level_rank_damage", "dict.get", '"effects"', 1),
        ("champions/shen.py", "_named_level_rank_damage", "dict.get", '"leveling"', 1),
        ("champions/shen.py", "_named_level_rank_damage", "dict.get", '"modifiers"', 1),
        ("champions/shen.py", "_named_level_rank_damage", "dict.get", '"units"', 1),
        ("champions/shen.py", "_named_level_rank_damage", "dict.get", '"values"', 1),
        (
            "champions/shyvana.py",
            "_scalemail_per_stack",
            "or-default",
            '"description"',
            1,
        ),
        ("champions/shyvana.py", "_scalemail_per_stack", "or-default", '"effects"', 1),
        (
            "champions/slotlib.py",
            "_find_primary_damage_leveling",
            "dict.get",
            '"attribute"',
            1,
        ),
        (
            "champions/slotlib.py",
            "_find_primary_damage_leveling",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "_find_primary_damage_leveling",
            "dict.get",
            '"leveling"',
            1,
        ),
        ("champions/slotlib.py", "_modifier_value", "dict.get", '"modifiers"', 1),
        ("champions/slotlib.py", "_modifier_value", "dict.get", '"values"', 1),
        ("champions/slotlib.py", "_require_seconds", "dict.get", '"units"', 1),
        ("champions/slotlib.py", "extract_cooldown", "dict.get", '"values"', 1),
        (
            "champions/slotlib.py",
            "extract_description_control_durations",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_control_durations",
            "or-default",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_damage_reduction",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_damage_reduction",
            "or-default",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_damage_reduction_cap",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_damage_reduction_cap",
            "or-default",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_duration",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_duration",
            "or-default",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_invulnerability_timing",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_invulnerability_timing",
            "or-default",
            '"effects"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_shield_duration",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/slotlib.py",
            "extract_description_shield_duration",
            "or-default",
            '"effects"',
            1,
        ),
        ("champions/slotlib.py", "extract_recharge", "or-default", '"rechargeRate"', 1),
        ("champions/slotlib.py", "extract_resource_cost", "dict.get", '"modifiers"', 1),
        ("champions/slotlib.py", "extract_resource_cost", "dict.get", '"values"', 1),
        ("champions/slotlib.py", "extract_resource_cost", "or-default", '"cost"', 1),
        ("champions/slotlib.py", "find_named_leveling", "dict.get", '"attribute"', 1),
        ("champions/slotlib.py", "find_named_leveling", "dict.get", '"effects"', 1),
        ("champions/slotlib.py", "find_named_leveling", "dict.get", '"leveling"', 1),
        ("champions/slotlib.py", "parse", "or-default", '"targeting"', 1),
        ("champions/slotlib.py", "sum_modifiers", "dict.get", '"modifiers"', 1),
        ("champions/slotlib.py", "sum_modifiers", "dict.get", '"units"', 1),
        ("champions/slotlib.py", "sum_modifiers", "dict.get", '"values"', 1),
        # Sona E's traversal defaults retired 2026-08-21: _celerity_grant
        # now indexes directly (KeyError is the fail-closed path).
        (
            "champions/syndra.py",
            "_dark_sphere_second_charge",
            "dict.get",
            '"resource"',
            1,
        ),
        ("champions/taric.py", "_bravado_window_terms", "dict.get", '"description"', 1),
        ("champions/taric.py", "_bravado_window_terms", "dict.get", '"effects"', 1),
        ("champions/taric.py", "_starlights_touch", "dict.get", '"description"', 1),
        ("champions/taric.py", "_starlights_touch", "dict.get", '"effects"', 1),
        (
            "champions/udyr.py",
            "_target_max_health_percent",
            "dict.get",
            '"modifiers"',
            1,
        ),
        ("champions/udyr.py", "_target_max_health_percent", "dict.get", '"units"', 1),
        ("champions/udyr.py", "_target_max_health_percent", "dict.get", '"values"', 1),
        ("champions/vi.py", "_carry_blast_shield", "dict.get", '"description"', 1),
        ("champions/vi.py", "_carry_blast_shield", "dict.get", '"effects"', 1),
        ("champions/viktor.py", "_siphon_shield", "dict.get", '"modifiers"', 1),
        ("champions/viktor.py", "_siphon_shield", "dict.get", '"units"', 1),
        ("champions/viktor.py", "_siphon_shield", "dict.get", '"values"', 1),
        ("champions/xayah.py", "_bladecaller", "dict.get", '"values"', 2),
        (
            "champions/xayah.py",
            "_secondary_feather_crit_extra",
            "dict.get",
            '"description"',
            1,
        ),
        (
            "champions/xayah.py",
            "_secondary_feather_crit_extra",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "champions/xayah.py",
            "_secondary_feather_ratio",
            "dict.get",
            '"description"',
            1,
        ),
        ("champions/xayah.py", "_secondary_feather_ratio", "dict.get", '"effects"', 1),
        (
            "champions/yasuo.py",
            "_per_target_lockout",
            "or-default",
            '"onTargetCdStatic"',
            1,
        ),
        (
            "champions/module_helpers.py",
            "q3_knockup_duration",
            "or-default",
            '"description"',
            1,
        ),
        (
            "champions/module_helpers.py",
            "q3_knockup_duration",
            "or-default",
            '"effects"',
            1,
        ),
        ("champions/yorick.py", "_leveling_flat_at_level", "dict.get", '"effects"', 1),
        ("champions/yorick.py", "_leveling_flat_at_level", "dict.get", '"leveling"', 1),
        (
            "champions/yorick.py",
            "_leveling_flat_at_level",
            "dict.get",
            '"modifiers"',
            1,
        ),
        ("champions/yorick.py", "_leveling_flat_at_level", "dict.get", '"units"', 1),
        ("champions/yorick.py", "_leveling_flat_at_level", "dict.get", '"values"', 1),
        ("champions/ziggs.py", "_short_fuse", "dict.get", '"cooldown"', 1),
        ("champions/ziggs.py", "_short_fuse", "dict.get", '"modifiers"', 1),
        ("champions/ziggs.py", "_short_fuse", "dict.get", '"values"', 1),
        (
            "champions/ziggs.py",
            "_short_fuse_refund_seconds",
            "dict.get",
            '"description"',
            1,
        ),
        (
            "champions/ziggs.py",
            "_short_fuse_refund_seconds",
            "dict.get",
            '"effects"',
            1,
        ),
        ("data_fetcher.py", "_item_name_index", "dict.get", '"name"', 1),
        ("data_updater.py", "reparse_cached_rune_effects", "dict.get", '"options"', 1),
        ("data_updater.py", "rune_roster", "dict.get", '"runes"', 1),
        ("data_updater.py", "rune_roster", "dict.get", '"slots"', 1),
        ("economics_data.py", "sourced_combine_cost", "dict.get", '"combine_costs"', 1),
        ("economics_data.py", "sourced_combine_cost", "or-default", '"id"', 1),
        ("economics_data.py", "sourced_combine_cost", "or-default", '"name"', 1),
        ("economics_data.py", "sourced_sell_value", "dict.get", '"per_item_sell"', 1),
        ("economics_data.py", "sourced_sell_value", "or-default", '"id"', 1),
        ("economics_data.py", "sourced_sell_value", "or-default", '"name"', 1),
        ("economics_data.py", "sourced_total", "dict.get", '"per_item_sell"', 1),
        ("economics_data.py", "sourced_total", "or-default", '"id"', 1),
        ("healing_helpers.py", "ability_json", "dict.get", '"abilities"', 1),
        ("healing_helpers.py", "leveling_modifier", "dict.get", '"effects"', 1),
        ("healing_helpers.py", "leveling_modifier", "dict.get", '"leveling"', 1),
        ("healing_helpers.py", "leveling_modifier", "dict.get", '"modifiers"', 1),
        ("healing_helpers.py", "leveling_modifier", "dict.get", '"values"', 1),
        ("healing_helpers.py", "leveling_ratio", "dict.get", '"effects"', 1),
        ("healing_helpers.py", "leveling_ratio", "dict.get", '"leveling"', 1),
        ("healing_helpers.py", "leveling_ratio", "dict.get", '"modifiers"', 1),
        ("healing_helpers.py", "leveling_ratio", "dict.get", '"units"', 1),
        ("healing_helpers.py", "leveling_ratio", "dict.get", '"values"', 1),
        ("healing_helpers.py", "leveling_value", "dict.get", '"effects"', 1),
        ("healing_helpers.py", "leveling_value", "dict.get", '"leveling"', 1),
        ("healing_helpers.py", "leveling_value", "dict.get", '"modifiers"', 1),
        ("healing_helpers.py", "leveling_value", "dict.get", '"values"', 1),
        (
            "interpreters/__init__.py",
            "uncompilable_item_receipt",
            "dict.get",
            '"name"',
            1,
        ),
        (
            "interpreters/delta_amp.py",
            "resolve_static_holder_amps",
            "dict.get",
            '"name"',
            1,
        ),
        ("interpreters/reactive.py", "thorns_effects", "dict.get", '"name"', 1),
        ("item_coverage.py", "is_unreviewed_fixture", "dict.get", '"name"', 1),
        ("item_coverage.py", "optimizer_candidate_coverage", "dict.get", '"name"', 1),
        ("item_coverage.py", "optimizer_supported_items", "dict.get", '"name"', 1),
        (
            "item_coverage.py",
            "require_calculation_item_coverage",
            "dict.get",
            '"name"',
            1,
        ),
        (
            "item_coverage.py",
            "require_certified_target_timeline",
            "dict.get",
            '"name"',
            2,
        ),
        (
            "item_coverage.py",
            "require_optimizer_item_coverage",
            "dict.get",
            '"name"',
            1,
        ),
        ("item_coverage.py", "target_item_model_coverage", "dict.get", '"name"', 1),
        ("item_source.py", "_champion_restriction", "or-default", '"champion"', 1),
        ("item_source.py", "_champion_restriction", "or-default", "key", 1),
        ("item_source.py", "_merge_effect_branches", "or-default", '"branches"', 1),
        ("item_source.py", "_merge_effect_branches", "or-default", '"effects"', 1),
        ("item_source.py", "_merge_one_item", "or-default", '"spec"', 1),
        ("item_source.py", "audit_scope", "or-default", "'name'", 1),
        ("item_source.py", "branch_inventory", "or-default", '"name"', 1),
        ("item_source.py", "branch_losses", "dict.get", "label", 1),
        ("item_source.py", "effect_entries", "or-default", '"active"', 1),
        ("item_source.py", "effect_entries", "or-default", '"passives"', 1),
        ("item_source.py", "item_source_audit", "or-default", '"name"', 2),
        ("item_source.py", "item_source_audit", "or-default", '"sourceWarnings"', 1),
        ("item_source.py", "merge_item_sources", "dict.get", 'item.get("id")', 1),
        (
            "item_source.py",
            "riot_declared_effects",
            "or-default",
            '"riotDescription"',
            1,
        ),
        ("item_source.py", "sr_availability", "dict.get", '"purchasable"', 1),
        ("item_source.py", "sr_availability", "or-default", '"acquisitionNote"', 1),
        ("item_source.py", "sr_availability", "or-default", '"championRestriction"', 1),
        ("item_source.py", "sr_availability", "or-default", '"modes"', 1),
        ("item_source.py", "sr_availability", "or-default", '"name"', 1),
        ("item_source.py", "sr_availability", "or-default", '"prices"', 1),
        ("item_source.py", "sr_availability", "or-default", '"rank"', 1),
        ("item_source.py", "sr_availability", "or-default", '"shop"', 1),
        ("passive_parser.py", "_find_active_by_name", "dict.get", '"active"', 1),
        ("passive_parser.py", "_find_active_by_name", "or-default", '"name"', 1),
        ("passive_parser.py", "_find_item_data_by_name", "dict.get", '"name"', 1),
        ("passive_parser.py", "_find_passive_by_name", "dict.get", '"passives"', 1),
        ("passive_parser.py", "_find_passive_by_name", "or-default", '"name"', 2),
        (
            "passive_parser.py",
            "parse_item_effect",
            "dict.get",
            '"criticalStrikeDamage"',
            1,
        ),
        ("passive_parser.py", "parse_item_effect", "dict.get", '"percent"', 1),
        ("passive_parser.py", "parse_item_effect", "dict.get", '"stats"', 1),
        ("rune_effects.py", "_shard_row", "dict.get", '"row"', 1),
        ("rune_effects.py", "_shard_row", "dict.get", '"slots"', 1),
        ("rune_effects.py", "_shard_row_options", "dict.get", '"options"', 1),
        ("rune_effects.py", "_shard_rows", "dict.get", '"row"', 1),
        ("rune_effects.py", "_shard_rows", "dict.get", '"slots"', 1),
        ("rune_effects.py", "_slot_word", "dict.get", '"row"', 1),
        ("rune_effects.py", "cached_effects", "dict.get", '"effects"', 1),
        ("rune_effects.py", "shard_catalog", "dict.get", '"name"', 2),
        ("rune_effects.py", "shard_catalog", "dict.get", '"options"', 1),
        ("rune_effects.py", "shard_catalog", "dict.get", '"row"', 2),
        ("rune_effects.py", "shard_catalog", "dict.get", '"slots"', 1),
        ("rune_effects.py", "validate_keystone_options", "dict.get", '"options"', 1),
        ("rune_parser.py", "_certify_roster_agreement", "dict.get", '"path"', 1),
        ("rune_parser.py", "_certify_roster_agreement", "dict.get", '"slot"', 1),
        ("rune_parser.py", "_parse_leveling", "dict.get", '"type"', 1),
        ("rune_parser.py", "rune_payload", "dict.get", "key", 1),
        ("stats.py", "_validate_cached_item_stats", "or-default", '"name"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"adaptiveType"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"attackSpeedRatio"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"attackType"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"flat"', 3),
        ("stats.py", "calculate_total_stats", "dict.get", '"healthRegen"', 2),
        ("stats.py", "calculate_total_stats", "dict.get", '"mana"', 2),
        ("stats.py", "calculate_total_stats", "dict.get", '"manaRegen"', 2),
        ("stats.py", "calculate_total_stats", "dict.get", '"perLevel"', 3),
        ("stats.py", "champion_stat_conversion", "dict.get", '"name"', 1),
        ("stats.py", "get_item_stats", "dict.get", '"name"', 1),
        ("stats.py", "get_item_stats", "dict.get", '"stats"', 1),
        ("stats.py", "get_item_stats", "or-default", '"name"', 1),
    }
)

#: A read on something this repository authored, not something it ingested:
#: the entry a slot parser just built, a champion module's reviewed packet
#: spec, an in-module lookup table.  An absent key is that declaration's own
#: statement that it carries no such facet, which is the shape
#: `ability_atoms.ABILITY_PAYLOAD_SCHEMA` formalises for the payloads that
#: cross a module boundary.
AUTHORED_DECLARATION = frozenset(
    {
        (
            "champions/__init__.py",
            "get_champion_option_rotation",
            "dict.get",
            '"key"',
            1,
        ),
        ("champions/ambessa.py", "_public_execution", "dict.get", '"parts"', 1),
        ("champions/ambessa.py", "_repudiation", "dict.get", '"name"', 1),
        ("champions/ambessa.py", "_repudiation", "dict.get", '"rank"', 1),
        ("champions/ambessa.py", "_repudiation", "or-default", '"rank"', 1),
        ("champions/amumu.py", "_apply_curse", "dict.get", '"parts"', 1),
        ("champions/aphelios.py", "parse", "dict.get", '"parts"', 1),
        ("champions/blitzcrank.py", "_rocket_grab", "dict.get", '"rank"', 1),
        ("champions/blitzcrank.py", "_rocket_grab", "or-default", '"rank"', 1),
        (
            "champions/camille.py",
            "_tactical_sweep_with_shield",
            "dict.get",
            '"rank"',
            1,
        ),
        (
            "champions/camille.py",
            "_tactical_sweep_with_shield",
            "or-default",
            '"rank"',
            1,
        ),
        (
            "champions/engine.py",
            "_apply_module_cc",
            "or-default",
            '"control_events"',
            1,
        ),
        ("champions/engine.py", "_apply_module_cc", "or-default", '"parts"', 1),
        ("champions/engine.py", "_certify_shared_instant", "or-default", '"parts"', 1),
        ("champions/engine.py", "_empower_marker_part", "dict.get", '"damage_type"', 1),
        (
            "champions/engine.py",
            "_refuse_undeclared_part_cc",
            "or-default",
            '"parts"',
            1,
        ),
        (
            "champions/engine.py",
            "_validate_cc_event_contract",
            "or-default",
            '"parts"',
            1,
        ),
        (
            "champions/engine.py",
            "_validate_entry_keys",
            "dict.get",
            '"post_hit_proc"',
            1,
        ),
        (
            "champions/engine.py",
            "_validate_entry_keys",
            "dict.get",
            '"target_debuff"',
            4,
        ),
        (
            "champions/engine.py",
            "_validate_entry_keys",
            "or-default",
            '"post_hit_proc"',
            2,
        ),
        ("champions/evelynn.py", "_allure", "dict.get", '"skillshot"', 1),
        ("champions/leblanc.py", "_mimic", "dict.get", "choice", 1),
        ("champions/malphite.py", "parse", "dict.get", '"rank"', 1),
        ("champions/malphite.py", "parse", "or-default", '"rank"', 1),
        ("champions/module_contract.py", "coverage", "dict.get", "slot", 1),
        ("champions/module_helpers.py", "parse", "dict.get", '"parts"', 1),
        ("champions/mordekaiser.py", "parse", "dict.get", "'detail'", 1),
        ("champions/nidalee.py", "parse", "dict.get", '"detail"', 1),
        ("champions/nidalee.py", "parse", "dict.get", '"total_raw"', 1),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "dict.get",
            '"count"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "dict.get",
            '"damage_type"',
            3,
        ),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "dict.get",
            '"total_raw"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "dict.get",
            "'name'",
            2,
        ),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "dict.get",
            "'tick_interval'",
            1,
        ),
        (
            "champions/packet_module.py",
            "_apply_packet_tick_fix",
            "or-default",
            '"total_raw"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_compiled_slot",
            "dict.get",
            '"damage_type"',
            1,
        ),
        ("champions/packet_module.py", "_compiled_slot", "dict.get", '"name"', 1),
        ("champions/packet_module.py", "_compiled_slot", "dict.get", '"ranks"', 1),
        ("champions/packet_module.py", "_compiled_slot", "dict.get", '"reason"', 1),
        ("champions/packet_module.py", "_one_hit", "dict.get", '"count"', 1),
        (
            "champions/packet_module.py",
            "_override_packet_static",
            "dict.get",
            '"base"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_override_packet_static",
            "dict.get",
            '"ratios"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_override_packet_static",
            "dict.get",
            '"stat"',
            1,
        ),
        (
            "champions/packet_module.py",
            "_override_packet_static",
            "dict.get",
            '"values"',
            1,
        ),
        ("champions/packet_module.py", "_single_hit_row", "dict.get", '"variants"', 1),
        (
            "champions/packet_module.py",
            "_variant_parsers",
            "dict.get",
            '"damage_type"',
            1,
        ),
        ("champions/packet_module.py", "_variant_parsers", "dict.get", '"name"', 1),
        ("champions/packet_module.py", "_variant_parsers", "dict.get", '"ranks"', 1),
        ("champions/packet_module.py", "_variant_parsers", "dict.get", '"reason"', 1),
        ("champions/packet_module.py", "_variant_slot", "dict.get", '"default"', 1),
        (
            "champions/packet_module.py",
            "build_packet_module",
            "dict.get",
            '"assumptions"',
            1,
        ),
        ("champions/packet_module.py", "build_packet_module", "dict.get", '"slots"', 2),
        ("champions/packet_module.py", "build_packet_module", "dict.get", "'slots'", 1),
        ("champions/packet_module.py", "parse", "dict.get", '"base"', 1),
        ("champions/packet_module.py", "parse", "dict.get", '"count"', 1),
        ("champions/packet_module.py", "parse", "dict.get", '"damage_type"', 2),
        ("champions/packet_module.py", "parse", "dict.get", '"ratios"', 1),
        ("champions/packet_module.py", "parse", "dict.get", '"stat"', 1),
        ("champions/packet_module.py", "parse", "dict.get", '"total_multiplier"', 1),
        ("champions/packet_module.py", "parse", "dict.get", '"values"', 1),
        ("champions/packet_module.py", "parse", "dict.get", "'tick_interval'", 1),
        (
            "champions/packet_module.py",
            "parse_abilities",
            "dict.get",
            '"damage_type"',
            1,
        ),
        ("champions/packet_module.py", "parse_abilities", "or-default", '"on_hit"', 1),
        ("champions/packet_module.py", "select_variant", "dict.get", '"default"', 1),
        ("champions/rakan.py", "_q_with_p_shield", "dict.get", '"rank"', 1),
        ("champions/rakan.py", "_q_with_p_shield", "or-default", '"rank"', 1),
        ("champions/samira.py", "parse", "dict.get", "'detail'", 1),
        ("champions/senna.py", "parse", "dict.get", '"name"', 1),
        ("champions/senna.py", "parse", "dict.get", '"rank"', 1),
        ("champions/senna.py", "parse", "or-default", '"rank"', 1),
        ("champions/shyvana.py", "derive_self_healing", "dict.get", '"detail"', 1),
        ("champions/slotlib.py", "parse", "dict.get", '"control_events"', 1),
        ("champions/slotlib.py", "parse", "dict.get", '"control_source_atoms"', 1),
        ("champions/slotlib.py", "parse", "dict.get", '"parts"', 1),
        ("champions/slotlib.py", "parse", "or-default", '"parts"', 1),
        ("champions/slotlib.py", "parse", "or-default", '"total_raw"', 1),
        ("champions/smolder.py", "parse", "dict.get", '"total_raw"', 2),
        ("champions/swain.py", "parse", "or-default", '"parts"', 1),
        ("champions/sylas.py", "parse", "or-default", '"parts"', 1),
        ("champions/teemo.py", "parse", "dict.get", '"detail"', 1),
        ("champions/teemo.py", "parse", "dict.get", '"total_raw"', 1),
        ("champions/vex.py", "parse", "dict.get", '"name"', 1),
        ("champions/vex.py", "parse", "dict.get", '"rank"', 1),
        ("champions/vex.py", "parse", "or-default", '"rank"', 1),
        ("champions/vi.py", "_carry_blast_shield", "dict.get", "'detail'", 1),
        ("champions/viktor.py", "parse", "dict.get", '"name"', 1),
        ("champions/viktor.py", "parse", "dict.get", '"rank"', 1),
        ("champions/viktor.py", "parse", "or-default", '"rank"', 1),
        ("champions/vladimir.py", "_apply_hemoplague", "dict.get", '"parts"', 1),
        ("champions/volibear.py", "parse", "dict.get", '"name"', 1),
        ("champions/volibear.py", "parse", "dict.get", '"rank"', 1),
        ("champions/volibear.py", "parse", "or-default", '"rank"', 1),
        ("champions/zac.py", "parse", "or-default", '"parts"', 1),
        ("champions/zed.py", "_death_mark", "dict.get", '"total_raw"', 1),
        ("champions/zed.py", "_death_mark", "or-default", '"total_raw"', 1),
        ("champions/zilean.py", "parse", "or-default", '"parts"', 1),
        ("champions/zoe.py", "_spell_thief", "dict.get", "summoner", 1),
        (
            "data_updater.py",
            "_riot_item_descriptions",
            "or-default",
            '"description"',
            1,
        ),
        ("data_updater.py", "reparse_cached_rune_effects", "dict.get", '"slots"', 1),
        ("healing_helpers.py", "parsed_rank", "dict.get", '"rank"', 1),
        ("healing_helpers.py", "parsed_rank", "dict.get", "slot", 1),
        ("healing_helpers.py", "parsed_rank", "or-default", '"rank"', 1),
        ("item_coverage.py", "_declared_families", "dict.get", '"type"', 1),
        ("item_coverage.py", "review_issue_refs", "dict.get", "str(item_name)", 1),
        ("item_source.py", "_effect_name", "or-default", '"name"', 1),
        ("item_source.py", "_merge_one_item", "or-default", '"name"', 1),
        ("item_source.py", "branch_inventory", "or-default", "'name'", 1),
        ("item_source.py", "branches", "or-default", '"branches"', 1),
        ("item_source.py", "item_source_audit", "or-default", '"name"', 2),
        ("rune_effects.py", "rune_catalog", "dict.get", '"icon"', 1),
        ("rune_effects.py", "rune_catalog", "dict.get", '"path"', 1),
        ("rune_paths/domination.py", "_compile_cheap_shot", "dict.get", '"effects"', 1),
        (
            "rune_paths/domination.py",
            "_compile_sudden_impact",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/domination.py",
            "_compile_taste_of_blood",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/domination.py",
            "_compile_ultimate_hunter",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/inspiration.py",
            "_compile_jack_of_all_trades",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/keystones.py", "_compile_aftershock", "dict.get", '"effects"', 1),
        (
            "rune_paths/keystones.py",
            "_compile_arcane_comet",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/keystones.py", "_compile_conqueror", "dict.get", '"effects"', 1),
        (
            "rune_paths/keystones.py",
            "_compile_dark_harvest",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/keystones.py", "_compile_deathfire", "dict.get", '"effects"', 1),
        ("rune_paths/keystones.py", "_compile_electrocute", "dict.get", '"effects"', 1),
        (
            "rune_paths/keystones.py",
            "_compile_first_strike",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/keystones.py", "_compile_fleet", "dict.get", '"effects"', 1),
        ("rune_paths/keystones.py", "_compile_glacial", "dict.get", '"effects"', 1),
        ("rune_paths/keystones.py", "_compile_grasp", "dict.get", '"effects"', 1),
        ("rune_paths/keystones.py", "_compile_guardian", "dict.get", '"effects"', 1),
        (
            "rune_paths/keystones.py",
            "_compile_hail_of_blades",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/keystones.py",
            "_compile_lethal_tempo",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/keystones.py",
            "_compile_press_the_attack",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/keystones.py", "_compile_stormraider", "dict.get", '"effects"', 1),
        ("rune_paths/keystones.py", "_compile_summon_aery", "dict.get", '"effects"', 1),
        ("rune_paths/precision.py", "_compile_absorb_life", "dict.get", '"effects"', 1),
        ("rune_paths/precision.py", "_compile_last_stand", "dict.get", '"effects"', 1),
        (
            "rune_paths/precision.py",
            "_compile_legend_alacrity",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/precision.py",
            "_compile_legend_bloodline",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/precision.py",
            "_compile_legend_haste",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/precision.py", "_compile_triumph", "dict.get", '"effects"', 1),
        ("rune_paths/resolve.py", "_compile_font_of_life", "dict.get", '"effects"', 1),
        ("rune_paths/resolve.py", "_compile_overgrowth", "dict.get", '"effects"', 1),
        ("rune_paths/resolve.py", "_compile_shield_bash", "dict.get", '"effects"', 1),
        ("rune_paths/shards.py", "compile_shard", "dict.get", '"effects"', 2),
        (
            "rune_paths/sorcery.py",
            "_compile_absolute_focus",
            "dict.get",
            '"effects"',
            1,
        ),
        (
            "rune_paths/sorcery.py",
            "_compile_axiom_arcanist",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/sorcery.py", "_compile_celerity", "dict.get", '"effects"', 1),
        (
            "rune_paths/sorcery.py",
            "_compile_gathering_storm",
            "dict.get",
            '"effects"',
            1,
        ),
        ("rune_paths/sorcery.py", "_compile_scorch", "dict.get", '"effects"', 1),
        ("rune_paths/sorcery.py", "_compile_transcendence", "dict.get", '"effects"', 1),
        ("rune_paths/sorcery.py", "_compile_waterwalking", "dict.get", '"effects"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"ability_haste"', 1),
        ("stats.py", "calculate_total_stats", "dict.get", '"ability_power"', 2),
    }
)

#: A row the engine built during this fight — a damage event, a cast, a heal
#: payment, a stat block `calculate_total_stats` produced.  Same class as
#: `ROW_READS`, and it retires the same way: one row dataclass per producer.
#: A build-stat read is *not* in here when a declared vocabulary covers it —
#: `champions.inputs.champion_stat` is the accessor, and rune, interpreter
#: and champion formulas all go through it.
ENGINE_ROW = frozenset(
    {
        ("champions/aatrox.py", "derive_self_healing", "dict.get", '"damage"', 2),
        ("champions/aatrox.py", "derive_self_healing", "dict.get", '"time"', 2),
        ("champions/alistar.py", "derive_self_healing", "dict.get", '"stacks"', 1),
        ("champions/alistar.py", "derive_self_healing", "dict.get", '"time"', 2),
        ("champions/alistar.py", "derive_self_healing", "or-default", '"stacks"', 1),
        ("champions/ambessa.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/ambessa.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/aphelios.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/briar.py", "derive_self_healing", "dict.get", '"damage"', 3),
        ("champions/briar.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/briar.py", "derive_self_healing", "or-default", '"damage"', 2),
        ("champions/briar.py", "derive_self_healing", "or-default", '"raw_damage"', 1),
        ("champions/camille.py", "derive_self_healing", "dict.get", '"damage"', 2),
        ("champions/camille.py", "derive_self_healing", "or-default", '"damage"', 1),
        (
            "champions/camille.py",
            "derive_self_healing",
            "or-default",
            '"raw_damage"',
            1,
        ),
        ("champions/chogath.py", "derive_self_healing", "dict.get", '"amount"', 1),
        ("champions/chogath.py", "derive_self_healing", "dict.get", '"kills"', 1),
        ("champions/chogath.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/chogath.py", "derive_self_healing", "or-default", '"amount"', 1),
        ("champions/chogath.py", "derive_self_healing", "or-default", '"kills"', 1),
        ("champions/darius.py", "derive_self_healing", "dict.get", '"sequence"', 1),
        ("champions/darius.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/darius.py", "derive_self_healing", "or-default", '"sequence"', 1),
        ("champions/dr_mundo.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/fiddlesticks.py", "derive_self_healing", "dict.get", '"damage"', 1),
        (
            "champions/fiddlesticks.py",
            "derive_self_healing",
            "or-default",
            '"raw_damage"',
            1,
        ),
        ("champions/gangplank.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/gragas.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/gwen.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/hecarim.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/hecarim.py", "derive_self_healing", "dict.get", '"time"', 2),
        ("champions/illaoi.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/janna.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/karma.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/kindred.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/maokai.py", "derive_self_healing", "dict.get", '"time"', 4),
        ("champions/milio.py", "derive_self_healing", "dict.get", '"time"', 2),
        ("champions/mordekaiser.py", "derive_self_healing", "dict.get", '"amount"', 1),
        (
            "champions/mordekaiser.py",
            "derive_self_healing",
            "or-default",
            '"amount"',
            1,
        ),
        ("champions/morgana.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/nasus.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/nidalee.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/nilah.py", "derive_self_healing", "dict.get", '"damage"', 2),
        ("champions/nunu_willump.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/rakan.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/reksai.py", "derive_self_healing", "dict.get", '"amount"', 1),
        ("champions/reksai.py", "derive_self_healing", "or-default", '"amount"', 1),
        ("champions/shyvana.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/shyvana.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/sona.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/soraka.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/sylas.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/sylas.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/tahm_kench.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/taric.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/trundle.py", "derive_self_healing", "dict.get", '"amount"', 1),
        ("champions/trundle.py", "derive_self_healing", "dict.get", '"damage"', 1),
        ("champions/trundle.py", "derive_self_healing", "dict.get", '"deaths"', 1),
        ("champions/trundle.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/trundle.py", "derive_self_healing", "or-default", '"amount"', 1),
        ("champions/trundle.py", "derive_self_healing", "or-default", '"deaths"', 1),
        (
            "champions/trundle.py",
            "derive_self_healing",
            "or-default",
            '"raw_damage"',
            1,
        ),
        ("champions/udyr.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/vi.py", "_denting_stream", "dict.get", '"E"', 1),
        ("champions/vi.py", "_denting_stream", "dict.get", '"Q"', 1),
        ("champions/vladimir.py", "derive_self_healing", "dict.get", '"damage"', 1),
        (
            "champions/vladimir.py",
            "derive_self_healing",
            "or-default",
            '"raw_damage"',
            1,
        ),
        ("champions/volibear.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/warwick.py", "derive_self_healing", "dict.get", '"damage"', 3),
        ("champions/xin_zhao.py", "derive_self_healing", "dict.get", '"damage"', 1),
        (
            "champions/xin_zhao.py",
            "derive_self_healing",
            "or-default",
            '"stacks_required"',
            1,
        ),
        ("champions/yorick.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/yuumi.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("champions/zac.py", "derive_self_healing", "dict.get", '"time"', 1),
        ("healing_helpers.py", "cast_slot_times", "dict.get", '"time"', 1),
        ("healing_helpers.py", "event_source", "dict.get", '"source_key"', 1),
        ("healing_helpers.py", "heal_from_damage", "dict.get", '"damage"', 1),
        ("healing_helpers.py", "heal_from_damage", "dict.get", '"time"', 1),
        ("healing_helpers.py", "payments", "dict.get", '"damage"', 1),
        ("healing_helpers.py", "payments", "dict.get", '"time"', 3),
        ("healing_helpers.py", "payments", "or-default", '"damage"', 1),
        ("healing_helpers.py", "trigger_fields", "dict.get", '"time"', 1),
        (
            "item_coverage.py",
            "require_certified_target_timeline",
            "dict.get",
            '"coarse_sources"',
            1,
        ),
        (
            "item_coverage.py",
            "require_certified_target_timeline",
            "dict.get",
            '"complete"',
            1,
        ),
        (
            "stats.py",
            "calculate_total_stats",
            "dict.get",
            '"armor_penetration_bonus_percent"',
            1,
        ),
        ("stats.py", "get_champion_base_stats", "dict.get", '"attackSpeedRatio"', 1),
    }
)

#: `getattr(module, "DECLARATION", None)` on a champion module, its parser,
#: or a compiled part.  The absent value is the module declining to declare
#: an optional contract, which `champions.module_contract` owns and validates;
#: it is a source fact about that module, not a cached-data miss.
MODULE_DECLARATION = frozenset(
    {
        (
            "champions/__init__.py",
            "get_champion_cast_order",
            "getattr",
            '"CAST_ORDER"',
            1,
        ),
        (
            "champions/__init__.py",
            "get_custom_cast_order_unavailable_reason",
            "getattr",
            '"CUSTOM_CAST_ORDER_UNAVAILABLE_REASON"',
            1,
        ),
        ("champions/ambessa.py", "<module>", "getattr", '"phase"', 1),
        ("champions/engine.py", "_apply_module_cc", "getattr", '"cc_kind"', 1),
        (
            "champions/engine.py",
            "_refuse_undeclared_part_cc",
            "getattr",
            '"cc_kind"',
            1,
        ),
        (
            "champions/engine.py",
            "_validate_cc_event_contract",
            "getattr",
            '"cc_duration"',
            1,
        ),
        (
            "champions/engine.py",
            "_validate_cc_event_contract",
            "getattr",
            '"cc_kind"',
            2,
        ),
        (
            "champions/module_contract.py",
            "_cast_dependencies",
            "getattr",
            '"CAST_ORDER"',
            1,
        ),
        (
            "champions/module_contract.py",
            "_coverage_channels",
            "getattr",
            '"COVERAGE_CHANNELS"',
            1,
        ),
        ("champions/module_contract.py", "_module_cc", "getattr", '"MODULE_CC"', 1),
        ("champions/module_contract.py", "_module_cc", "getattr", '"cc_kinds"', 1),
        ("champions/module_contract.py", "_module_cc", "getattr", '"packet_sha256"', 1),
        (
            "champions/module_contract.py",
            "_packet_declaration",
            "getattr",
            '"packet_sha256"',
            1,
        ),
        ("champions/module_contract.py", "_present", "getattr", "attribute", 1),
        ("champions/module_contract.py", "_require_list", "getattr", "field_name", 1),
        (
            "champions/module_contract.py",
            "_stat_conversion",
            "getattr",
            '"MODULE_STAT_CONVERSION"',
            1,
        ),
        (
            "champions/module_contract.py",
            "_ultimate_recasts",
            "getattr",
            '"ULTIMATE_RECASTS"',
            1,
        ),
        (
            "champions/module_contract.py",
            "contract_from_module",
            "getattr",
            '"MODULE_COVERAGE"',
            1,
        ),
        (
            "champions/module_contract.py",
            "contract_from_module",
            "getattr",
            '"SLOTS"',
            1,
        ),
        (
            "champions/module_contract.py",
            "contract_from_module",
            "getattr",
            '"parse_abilities"',
            1,
        ),
        ("champions/nocturne.py", "_tether_fear", "getattr", '"phase"', 1),
        ("champions/packet_module.py", "_variant_slot", "getattr", '"phase"', 1),
        ("data_updater.py", "_process_champions", "getattr", '"name"', 1),
        (
            "interpreters/__init__.py",
            "_validate_authority_agreement",
            "getattr",
            '"subject"',
            1,
        ),
        (
            "interpreters/cast_proc.py",
            "self_shield_owners",
            "getattr",
            '"self_shield"',
            1,
        ),
        ("interpreters/defense_state.py", "_policy_reference", "getattr", "name", 1),
        ("item_coverage.py", "_prices_holder_durability", "getattr", "field", 1),
    }
)

#: The covered set: files and directories every `.py` under which is
#: scanned.  The rest of `src/calculator` is the declared tail (ER5).
ROOTS = (
    "damage.py",
    "item_effects.py",
    "ability_atoms.py",
    "champions",
    "rune_paths",
    "interpreters",
    "rune_effects.py",
    "rune_parser.py",
    "item_source.py",
    "item_coverage.py",
    "healing_helpers.py",
    "economics_data.py",
    "data_fetcher.py",
    "data_updater.py",
    "passive_parser.py",
    "stats.py",
    "__init__.py",
    "ability_spec.py",
    "application_errors.py",
    "binary_roots.py",
    "capabilities.py",
    "cast_dependency.py",
    "coverage_evidence.py",
    "data_registry.py",
    "item_outcomes.py",
    "minion_stats.py",
    "patch_identity.py",
    "program/__init__.py",
    "program/amp.py",
    "program/dependency.py",
    "program/identity.py",
    "program/precision.py",
    "program/route.py",
    "program/scope.py",
    "program/views/breakdown.py",
    "program/views/tdd.py",
    "request_parsing.py",
    "resistance.py",
    "role_quests.py",
    "shield_ledger.py",
    "stat_conversion.py",
    "survival/__init__.py",
    "survival/accumulate.py",
    "survival/pricing.py",
    "value_ref.py",
    "work_counters.py",
)

#: The frontier as backlog ER5 found it: every `src/calculator` module the
#: pin did not reach.  These are the request, timeline, program and survival
#: layers, whose surviving sites are overwhelmingly engine rows — the
#: `ROW_READS` class, which retires with a row dataclass per producer rather
#: than one conversion at a time.
#:
#: **This tuple is a record, not a setting.**  A module leaves it by joining
#: `ROOTS`; adding one back is undoing finished work, and the test below
#: exists so that undoing it cannot be done by deletion alone.
ER5_TAIL = (
    "ally_effects.py",
    "atomizer.py",
    "atomizer_domains.py",
    "auto_attack_policy.py",
    "bis.py",
    "calculate.py",
    "certainty.py",
    "cleanse_eligibility.py",
    "crowd_control_eligibility.py",
    "defensive_effects.py",
    "delivery_eligibility.py",
    "economy.py",
    "healing.py",
    "healing_reduction.py",
    "interaction_effects.py",
    "item_behavior.py",
    "item_behavior_catalog.py",
    "item_support_effects.py",
    "ledger_projection.py",
    "loadout_rules.py",
    "optimizer.py",
    "participant_timeline.py",
    "pipeline.py",
    "practice_dummy.py",
    "program/build.py",
    "program/caches.py",
    "program/compile.py",
    "program/events.py",
    "program/rung.py",
    "program/views/__init__.py",
    "program/views/receipt.py",
    "program/views/score.py",
    "program/views/survival.py",
    "program/walk.py",
    "public_response.py",
    "resource_ledger.py",
    "roster_composition.py",
    "rotation_resolver.py",
    "scenario.py",
    "spatial.py",
    "state_lifecycle.py",
    "support_effects.py",
    "survival/actions.py",
    "survival/compile.py",
    "survival/outcome_state.py",
    "survival/receipt_state.py",
    "survival/score_state.py",
    "survival/transitions.py",
    "timeline_coverage.py",
    "trigger_stream.py",
    "validation_receipts.py",
)

#: Every bucket, and the covered set they must exactly account for.
SURVIVORS = (
    ROW_READS
    | REQUEST_ITEM_STATE
    | OPTION_SCHEMA
    | LOADOUT_NAMES
    | ATOM_ROWS
    | WIKI_TRAVERSALS
    | CACHED_SOURCE_ROW
    | AUTHORED_DECLARATION
    | ENGINE_ROW
    | MODULE_DECLARATION
)

#: Receivers that carry a champion-module-authored ability payload.  A literal
#: default on one of these is what `ability_atoms.ABILITY_PAYLOAD_SCHEMA`
#: exists to refuse, so the count is pinned at zero rather than allowlisted.
PAYLOAD_RECEIVERS = (
    "ability.",
    "ability_damages",
    "ability_info",
    "auto_attack_override.",
    "conversion_info.",
    "crit_modifier.",
    "debuff.",
    "info.",
    "on_hit.",
    "on_hit_data.",
    "on_hit_spec.",
    "r_info.",
    "spec.",
    "state.ability_damages",
    "storage.",
    "target_debuff.",
)


def _covered_files():
    """Every `.py` the covered roots hold, as paths under `src/calculator`."""
    return sorted(literal_defaults.targets(str(CALCULATOR / root) for root in ROOTS))


def _findings(name="damage.py"):
    return literal_defaults.scan([CALCULATOR / name])


def _covered_findings():
    """Every surviving site in the covered set, keyed the way `SURVIVORS` is.

    The occurrence count rides the key because the other four fields do not
    separate two sites in one function reading one key: without it a second
    such site hides inside the first one's frozen row.
    """
    occurrences = Counter(
        (
            Path(finding.path).resolve().relative_to(CALCULATOR).as_posix(),
            finding.enclosing,
            finding.kind,
            finding.key,
        )
        for finding in literal_defaults.scan(_covered_files())
    )
    return {(*key, count) for key, count in occurrences.items()}


def test_no_ability_payload_read_carries_a_literal_default():
    """Bucket A is zero: every payload field goes through ability_atoms."""
    offenders = [
        f"{finding.line}: {finding.expression}"
        for finding in _findings()
        if finding.expression.startswith(PAYLOAD_RECEIVERS)
    ]
    assert offenders == []


def test_the_surviving_literal_defaults_are_the_frozen_ones():
    """Nothing new joins a bucket, and a retired row leaves it."""
    found = _covered_findings()
    assert found - SURVIVORS == set()
    assert SURVIVORS - found == set()


def test_every_covered_root_exists():
    """A root renamed out from under the pin fails here, not silently."""
    missing = [root for root in ROOTS if not (CALCULATOR / root).exists()]
    assert missing == []


def test_the_frontier_only_ever_moves_towards_the_covered_set():
    """A module may join `ROOTS`; nothing may fall out of it.

    `ER5_TAIL` is a record of what was uncovered when the pin landed, so the
    subset is one-directional by construction: converting a tail module
    shrinks the left side, and demoting a covered one puts a name on the left
    that the right does not hold.  A module new to the package lands there
    too, so it fails closed until somebody decides which side it is on.
    """
    covered = {path.resolve() for path in _covered_files()}
    everything = {path.resolve() for path in CALCULATOR.rglob("*.py")}
    uncovered = {
        path.relative_to(CALCULATOR).as_posix() for path in everything - covered
    }
    assert covered <= everything
    assert uncovered - set(ER5_TAIL) == set()


def test_the_scanner_still_finds_a_planted_cached_data_default(tmp_path):
    """The gate is driven by a real scan, not by an empty one."""
    planted = tmp_path / "planted.py"
    planted.write_text(
        "def f(info):" + chr(10) + "    return info.get('dot_duration', 0.0)" + chr(10),
        encoding="utf-8",
    )
    assert [f.key for f in literal_defaults.scan([planted])] == ["'dot_duration'"]


def test_an_accumulator_index_and_a_none_coalesce_stay_exempt(tmp_path):
    """Both exemptions are shape rules, so a planted pair proves them."""
    planted = tmp_path / "exempt.py"
    planted.write_text(
        "def f(by_type, dtype, maybe):"
        + chr(10)
        + "    return by_type.get(dtype, 0.0), (maybe or 0.0)"
        + chr(10),
        encoding="utf-8",
    )
    assert literal_defaults.scan([planted]) == []
