"""The Stardust stack pool, and what a Q burst and an E execute are worth per stack."""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Any, NamedTuple

from ..binary_roots import data_value, spell_object
from .source_receipts import state_receipt

_Q_BURSTS_PER_CHANNEL = 3


# The Stardust/execute constants are ROOTED IN THE BINARY, not hand-copied:
# the wiki modifier parser degrades (Q burst: values [0,...], units
# "(3.1% Stardust)% of target's maximum health") and the E execute threshold
# has no champion-JSON entry at all, so the values resolve through
# ``binary_roots`` from data/bin/characters/aurelionsol.bin.json (client
# 16.15.8024387).  A patch that moves a root moves the module with it; a dump
# that goes missing fails closed at import.
# https://wiki.leagueoflegends.com/en-us/Aurelion_Sol
_Q_SPELL = spell_object("Aurelion Sol", "AurelionSolQ")


_E_SPELL = spell_object("Aurelion Sol", "AurelionSolE")


_Q_BURST_MAXHP_PCT_PER_STARDUST = (
    data_value(_Q_SPELL, "QMaxHealthTrueDamagePerStack") * 100.0
)  # % of target max HP per stack (binary stores the fraction)


_E_EXECUTE_BASE_PCT = data_value(_E_SPELL, "BaseExecutionThreshold")


_E_EXECUTE_PCT_PER_100_STARDUST = (
    data_value(_E_SPELL, "ExecutionGrowthPerBreakpoint") * 100.0
)  # per-stack growth, displayed per 100 Stardust


# Stardust generation (wiki: the beam burst "generates 2 Stardust if they
# are a champion").
_STARDUST_PER_Q_BURST = data_value(_Q_SPELL, "QMassStolen")


class _StardustRule(NamedTuple):
    """The typed Stardust (Cosmic Creator) counter declaration.

    Stardust is a PERMANENT counter generated by damaging abilities:
    the Q burst grants +2 per champion hit, E grants +1 per full second
    a champion is in the zone plus kill bounties (2/2/1), and R grants
    +5 per enemy champion hit.  Champion takedowns themselves grant NO
    Stardust (they only refund W's cooldown).  Both priced terms are
    continuous LINEAR in stacks (Q burst +0.031% max HP per stack; E
    execute 5% + 2.6% per 100); the per-100 rows are display milestones
    only.  ``public_receipt()`` rides the option's ``state`` and the
    resource-ledger stardust declaration.

    The execute terms carry three published spellings, each bound to the
    same constant below, because the API ships all three.
    """

    per_stack_burst_maxhp_pct: float
    q_burst_maxhp_pct_per_100: float
    execute_base_pct: float
    execute_pct_per_100: float
    execute_pct_per_100_stacks: float
    e_execute_base_pct: float
    e_execute_pct_per_100: float
    stardust_per_q_burst: float
    bursts_per_q_channel: int
    execute_breakpoint_stacks: int
    max_stacks: int
    atom_ids: Mapping[str, Mapping[str, str]]
    certified_constants: Mapping[str, float]
    permanent: bool
    source: Mapping[str, Any]

    def public_receipt(self) -> dict[str, Any]:
        """The published Stardust declaration."""
        return state_receipt("Aurelion Sol — Cosmic Creator (Stardust)", self)


# Atom-backed certification surface: every priced constant maps to its
# evidence root.  The Q burst's Stardust term roots in the HALF-PARSED atom
# (values zeroed, the 3.1% lives in the units string, d7b0a266cad8da3f) with
# the binary QMaxHealthTrueDamagePerStack 0.00031 as the value root; the E
# execute constants have no JSON home (the binary BaseExecutionThreshold 5.0
# / ExecutionGrowthPerBreakpoint 0.026 are the root); the +2/burst roots in
# the binary QMassStolen 2.0.  The certified values the atom ids map are
# pinned beside them, so a patch that moves an atom or a binary root trips
# the tests rather than drifting silently.
_PER_STACK_BURST_MAXHP_PCT = 0.031

AURELION_SOL_STARDUST_RULE = _StardustRule(
    per_stack_burst_maxhp_pct=_PER_STACK_BURST_MAXHP_PCT,
    q_burst_maxhp_pct_per_100=3.1,
    execute_base_pct=_E_EXECUTE_BASE_PCT,
    execute_pct_per_100=_E_EXECUTE_PCT_PER_100_STARDUST,
    execute_pct_per_100_stacks=_E_EXECUTE_PCT_PER_100_STARDUST,
    e_execute_base_pct=_E_EXECUTE_BASE_PCT,
    e_execute_pct_per_100=_E_EXECUTE_PCT_PER_100_STARDUST,
    stardust_per_q_burst=_STARDUST_PER_Q_BURST,
    bursts_per_q_channel=_Q_BURSTS_PER_CHANNEL,
    execute_breakpoint_stacks=100,  # the per-100 milestone step
    max_stacks=999,  # the ledger/API bound (the cache's cap)
    atom_ids=MappingProxyType(
        {
            "per_stack_burst_maxhp_pct": MappingProxyType(
                {
                    "atom_id": "ability.bonus _magic _damage.modifier_2",
                    "hash": "d7b0a266cad8da3f",
                }
            ),
            "execute_base_pct": MappingProxyType(
                {"atom_id": "binary:BaseExecutionThreshold", "hash": ""}
            ),
            "execute_pct_per_100": MappingProxyType(
                {"atom_id": "binary:ExecutionGrowthPerBreakpoint", "hash": ""}
            ),
            "stardust_per_q_burst": MappingProxyType(
                {"atom_id": "binary:QMassStolen", "hash": ""}
            ),
        }
    ),
    certified_constants=MappingProxyType(
        {
            "per_stack_burst_maxhp_pct": _PER_STACK_BURST_MAXHP_PCT,
            "execute_base_pct": _E_EXECUTE_BASE_PCT,
            "execute_pct_per_100": _E_EXECUTE_PCT_PER_100_STARDUST,
            "stardust_per_q_burst": _STARDUST_PER_Q_BURST,
        }
    ),
    permanent=True,
    source=MappingProxyType(
        {
            "label": (
                "Local League Wiki cache — Aurelion Sol P (Cosmic Creator) "
                "Stardust prose; values binary-confirmed in the local "
                "Community Dragon cache (aurelionsol.bin.json 16.15.8024387)"
            ),
            "url": "https://wiki.leagueoflegends.com/en-us/Aurelion_Sol",
            "revision_id": 3952788,
            "revision_timestamp": "2025-09-10T01:55:29Z",
        }
    ),
)
