"""The Stardust stack pool, and what a Q burst and an E execute are worth per stack."""

from typing import Any

from ..binary_roots import data_value, spell_object

_Q_BURSTS_PER_CHANNEL = 3


# The Stardust/execute constants are ROOTED IN THE BINARY, not hand-copied:
# the wiki modifier parser degrades (Q burst: values [0,...], units
# "(3.1% Stardust)% of target's maximum health") and the E execute threshold
# has no champion-JSON entry at all, so the values resolve through
# ``binary_roots`` from data/bin/characters/aurelionsol.bin.json (client
# 16.15.8024387).  A patch that moves a root moves the module with it; a dump
# that goes missing fails closed at import.
# https://wiki.leagueoflegends.com/en-us/Aurelion_Sol
_Q_SPELL = spell_object("Aurelion Sol", "AurelionSolQ")


_E_SPELL = spell_object("Aurelion Sol", "AurelionSolE")


_Q_BURST_MAXHP_PCT_PER_STARDUST = (
    data_value(_Q_SPELL, "QMaxHealthTrueDamagePerStack") * 100.0
)  # % of target max HP per stack (binary stores the fraction)


_E_EXECUTE_BASE_PCT = data_value(_E_SPELL, "BaseExecutionThreshold")


_E_EXECUTE_PCT_PER_100_STARDUST = (
    data_value(_E_SPELL, "ExecutionGrowthPerBreakpoint") * 100.0
)  # per-stack growth, displayed per 100 Stardust


# Stardust generation (wiki: the beam burst "generates 2 Stardust if they
# are a champion").
_STARDUST_PER_Q_BURST = data_value(_Q_SPELL, "QMassStolen")


class _StardustRule:
    """The typed Stardust (Cosmic Creator) counter declaration (P3 3X).

    Stardust is a PERMANENT counter generated by damaging abilities:
    the Q burst grants +2 per champion hit, E grants +1 per full second
    a champion is in the zone plus kill bounties (2/2/1), and R grants
    +5 per enemy champion hit — champion takedowns themselves grant NO
    Stardust (they only refund W's cooldown).  Both priced terms are
    continuous LINEAR in stacks (Q burst +0.031% max HP per stack; E
    execute 5% + 2.6% per 100); the per-100 rows are display milestones
    only.  ``public_receipt()`` rides the option's ``state`` and the
    resource-ledger stardust declaration.
    """

    def __init__(self) -> None:
        self.q_burst_maxhp_pct_per_100 = 3.1
        self.e_execute_base_pct = _E_EXECUTE_BASE_PCT
        self.e_execute_pct_per_100 = _E_EXECUTE_PCT_PER_100_STARDUST
        self.stardust_per_q_burst = _STARDUST_PER_Q_BURST
        self.bursts_per_q_channel = _Q_BURSTS_PER_CHANNEL
        self.execute_breakpoint_stacks = 100  # the per-100 milestone step
        self.max_stacks = 999  # the ledger/API bound (the cache's cap)
        self.permanent = True
        # Atom-backed certification surface (P4/P1): every priced constant
        # maps to its evidence root.  The Q burst's Stardust term roots in
        # the HALF-PARSED atom (values zeroed, the 3.1% lives in the units
        # string — d7b0a266cad8da3f) with the binary
        # QMaxHealthTrueDamagePerStack 0.00031 as the value root; the E
        # execute constants have no JSON home (the binary
        # BaseExecutionThreshold 5.0 / ExecutionGrowthPerBreakpoint 0.026
        # are the root); the +2/burst roots in the binary QMassStolen 2.0.
        self.atom_ids = {
            "per_stack_burst_maxhp_pct": {
                "atom_id": "ability.bonus _magic _damage.modifier_2",
                "hash": "d7b0a266cad8da3f",
            },
            "execute_base_pct": {
                "atom_id": "binary:BaseExecutionThreshold",
                "hash": "",
            },
            "execute_pct_per_100": {
                "atom_id": "binary:ExecutionGrowthPerBreakpoint",
                "hash": "",
            },
            "stardust_per_q_burst": {
                "atom_id": "binary:QMassStolen",
                "hash": "",
            },
        }
        # The certified values the atom_ids map (fail-closed staleness:
        # the hashes are pinned; a patch that changes the atoms or the
        # binary roots trips the tests, never a silent drift).
        self.certified_constants = {
            "per_stack_burst_maxhp_pct": 0.031,
            "execute_base_pct": self.e_execute_base_pct,
            "execute_pct_per_100": self.e_execute_pct_per_100,
            "stardust_per_q_burst": self.stardust_per_q_burst,
        }
        self.source = {
            "label": (
                "Local League Wiki cache — Aurelion Sol P (Cosmic Creator) "
                "Stardust prose; values binary-confirmed in the local "
                "Community Dragon cache (aurelionsol.bin.json 16.15.8024387)"
            ),
            "url": "https://wiki.leagueoflegends.com/en-us/Aurelion_Sol",
            "revision_id": 3952788,
            "revision_timestamp": "2025-09-10T01:55:29Z",
        }

    def public_receipt(self) -> dict[str, Any]:
        return {
            "name": "Aurelion Sol — Cosmic Creator (Stardust)",
            "per_stack_burst_maxhp_pct": 0.031,
            "q_burst_maxhp_pct_per_100": self.q_burst_maxhp_pct_per_100,
            "execute_base_pct": self.e_execute_base_pct,
            "execute_pct_per_100": self.e_execute_pct_per_100,
            "execute_pct_per_100_stacks": self.e_execute_pct_per_100,
            "e_execute_base_pct": self.e_execute_base_pct,
            "e_execute_pct_per_100": self.e_execute_pct_per_100,
            "stardust_per_q_burst": self.stardust_per_q_burst,
            "bursts_per_q_channel": self.bursts_per_q_channel,
            "execute_breakpoint_stacks": self.execute_breakpoint_stacks,
            "max_stacks": self.max_stacks,
            "atom_ids": {key: dict(value) for key, value in self.atom_ids.items()},
            "certified_constants": dict(self.certified_constants),
            "permanent": self.permanent,
            "source": dict(self.source),
        }


AURELION_SOL_STARDUST_RULE = _StardustRule()
