"""Regenerate the certified damage-cast table from the registered modules.

Every Q/W/E/R entry a registered champion module prices as damage or control
against an enemy becomes one certified authored cast: an area entry
(``area_damage``, stamped from the cached ``spellEffects``) reaches every
enemy the roster holds, any other entry reaches the one enemy named. The
table is written to ``src/calculator/certified_casts.py`` and read by
``combat_events.combat_event_contract``; ``tests/test_combat_events.py`` runs
this module's ``--check`` so a slot the modules start or stop pricing fails
closed there.

Usage::

    python scripts/certify_damage_casts.py --write
    python scripts/certify_damage_casts.py --check
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.calculator.champions import (  # noqa: E402  pylint: disable=wrong-import-position
    _CHAMPION_MODULES,
    get_custom_cast_order_unavailable_reason,
    parse_champion_abilities,
)
from src.calculator.combat_events import (  # noqa: E402  pylint: disable=wrong-import-position
    CERTIFIED_ENEMY_CASTS,
    CERTIFIED_SUPPORT_CASTS,
)
from src.calculator.data_fetcher import (
    get_champion,
)  # noqa: E402  pylint: disable=wrong-import-position

TARGET = ROOT / "src" / "calculator" / "certified_casts.py"
SLOTS = ("Q", "W", "E", "R")
# A representative level-18 stat sheet: only the *presence* of a priced part
# is read, never its value, so the numbers here decide nothing.
_STATS = {
    "attack_damage": 150.0,
    "bonus_attack_damage": 80.0,
    "ability_power": 100.0,
    "health": 2500.0,
    "bonus_health": 800.0,
    "armor": 100.0,
    "magic_resist": 50.0,
    "attack_speed": 1.2,
    "attack_speed_ratio": 0.7,
    "bonus_attack_speed": 40.0,
    "critical_strike_chance": 0.0,
}
_TARGET = {"health": 2000.0, "max_health": 2000.0, "armor": 100.0, "mr": 60.0}


def _prices_an_enemy(entry: dict) -> bool:
    parts = tuple(entry.get("parts") or ())
    damage = any(
        (getattr(part, "amount", 0.0) or 0.0) > 0.0
        or getattr(part, "hp_scaled_damage", None) is not None
        for part in parts
    ) or bool(entry.get("dot_duration"))
    control = bool(entry.get("control_events")) or any(
        getattr(part, "cc_kind", None) not in (None, "none") for part in parts
    )
    return damage or control


def derive() -> dict[tuple[str, str], str]:
    """(champion, slot) -> reach for every priced enemy-facing cast."""
    table: dict[tuple[str, str], str] = {}
    for name in sorted(_CHAMPION_MODULES):
        # A module that keeps its certified cast sequence (Vi, Kai'Sa,
        # Karthus) cannot take an authored slot on its own; the request
        # would be refused with the module's own reason, so nothing here
        # advertises it.
        if get_custom_cast_order_unavailable_reason(name):
            continue
        entries = parse_champion_abilities(
            get_champion(name),
            18,
            _STATS["ability_power"],
            {"Q": 5, "W": 5, "E": 5, "R": 3},
            champion_stats=dict(_STATS),
            target_stats=dict(_TARGET),
        )
        for slot in SLOTS:
            # A hand-reviewed table (an ally cast whose control is a side
            # effect, Lulu R; a reviewed enemy cast) keeps its own recipients.
            if (name, slot) in CERTIFIED_SUPPORT_CASTS or (
                name,
                slot,
            ) in CERTIFIED_ENEMY_CASTS:
                continue
            entry = entries.get(slot)
            if isinstance(entry, dict) and _prices_an_enemy(entry):
                table[(name, slot)] = (
                    "every_enemy" if entry.get("area_damage") else "one_enemy"
                )
    return table


def render(table: dict[tuple[str, str], str]) -> str:
    lines = [
        '"""Certified authored damage casts, one line per priced enemy-facing slot.',
        "",
        "Generated by scripts/certify_damage_casts.py from the registered champion",
        "modules; regenerate it, never hand-edit it. The reach is the cached",
        "``spellEffects`` stamp: an area cast reaches every enemy the roster holds,",
        "any other reaches the one enemy an authored cast names.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "CERTIFIED_DAMAGE_CASTS: dict[tuple[str, str], str] = {",
    ]
    for (name, slot), reach in sorted(
        table.items(), key=lambda item: (item[0][0], SLOTS.index(item[0][1]))
    ):
        lines.append(f'    ("{name}", "{slot}"): "{reach}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = render(derive())
    if args.write:
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return 0
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if current != text:
        print("certified_casts.py differs from the registered modules; run --write")
        return 1
    print("certified_casts.py matches the registered modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
