import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
process.chdir(fileURLToPath(new URL(".", import.meta.url)));
const check = process.argv.includes("--check");

/* The scoreboard matcher is Skyway's classic script for the advanced page.
 * Its DOM-free half is republished here as an ES module, so the shared
 * calculator (this page and the Scryglass tab) bundles the same code rather
 * than a copy or a page-level global. Everything before the page wiring
 * marker is the matcher; the module adds one export line. */
const matcherSource = await readFile("../static/js/scoreboard.js", "utf8");
const wiringAt = matcherSource.indexOf("/* --- page wiring");
if (wiringAt < 0) throw new Error("scoreboard.js has no page wiring marker");
const matcherModule =
  "/* Generated by ui/build.mjs from static/js/scoreboard.js. Do not edit. */\n" +
  matcherSource.slice(0, wiringAt).trimEnd() +
  "\n\nexport { ScoreboardVision };\n";
const matcherPath = "src/scoreboard-vision.js";
/* Every generated string and esbuild buffer is LF, while a checkout under
 * core.autocrlf is CRLF, so both comparisons below normalise first. All the
 * compared assets are UTF-8 text. */
const asLf = (text) => text.replace(/\r\n/g, "\n");
if (check) {
  const current = await readFile(matcherPath, "utf8").catch(() => "");
  if (asLf(current) !== asLf(matcherModule))
    throw new Error(`Generated asset differs: ${matcherPath}`);
} else {
  await writeFile(matcherPath, matcherModule);
}

const result = await build({
  absWorkingDir: fileURLToPath(new URL(".", import.meta.url)),
  entryPoints: ["src/standalone.tsx"],
  bundle: true,
  minify: true,
  format: "esm",
  target: ["es2022"],
  outdir: "../static/calculator",
  entryNames: "calculator",
  legalComments: "external",
  define: { "process.env.NODE_ENV": '"production"' },
  write: false,
});
result.outputFiles.push({
  path: fileURLToPath(
    new URL("../static/calculator/favicon.svg", import.meta.url),
  ),
  contents: await readFile(new URL("assets/favicon.svg", import.meta.url)),
});
for (const file of result.outputFiles) {
  if (check) {
    const current = await readFile(file.path, "utf8");
    if (asLf(current) !== asLf(Buffer.from(file.contents).toString("utf8")))
      throw new Error(`Generated asset differs: ${file.path}`);
  } else {
    await mkdir(new URL("../static/calculator/", import.meta.url), {
      recursive: true,
    });
    await writeFile(file.path, file.contents);
  }
}
console.log(
  check ? "Calculator assets match source." : "Calculator assets built.",
);
